### ISSUE TITLE
Neovim pasting content with ^M at the end of lines

### ISSUE THREAD

**Issue by MichaelAquilina** [neovim/neovim#10223]
- `nvim --version`: NVIM v0.3.7
- Vim (version: ) VIM - Vi IMproved 8.1 (2018 May 18). Pasting does not work at all on Vim
- Operating system/version: OpenSUSE Tumbleweed running Sway (Wayland)
- Terminal name/version: tilix
- `$TERM`: xterm-256-color

### Steps to reproduce using `nvim -u NORC`

Copy some content (e.g. from Firefox) containing mulitple lines. Open nvim in safe mode
```
nvim -u NORC
```
Paste content using `"+P` and notice ^M and the end of each line.

Interestingly, pasting directly from the terminal by entering insert mode and then pasting using shift+ctrl+v pastes the content correctly.

Some other interesting pieces of information from neovim:
```
set ff?
  fileformat=unix 
```
```
set ffs?
  fileformats=unix,dos
```

### Expected behaviour
Lines are pasted to neovim without ^M at the end of each line.

**Comment by blueyed** [comment]
What does `:checkhealth provider` say about "Clipboard"?

(I am not seeing this issue)

**Comment by MichaelAquilina** [comment]
```
## Clipboard (optional)
  - OK: Clipboard tool found: wl-copy
```

there is also the corresponding `wl-paste` command installed.

**Comment by MichaelAquilina** [comment]
I *might* be using the rust version of wl-clipboard (I cant recall if I had moved off from it)

https://github.com/YaLTeR/wl-clipboard-rs

**Comment by blueyed** [comment]
Might be an issue with wl-copy/wl-paste then.
Check if using "xclip" works for you (which I am using), and/or the raw output of `wl-paste` (using e.g. `| cat -A`).

Code ref: https://github.com/blueyed/neovim/blob/5a7590b46fdb7edfb7b5b56a92a59eda2a95d1a6/runtime/autoload/provider/clipboard.vim#L75-L80

**Comment by MichaelAquilina** [comment]
Tried installing the official `wl-clipboard` from OpenSUSEs repos and it had the same issue.

when piping to `cat -A` as you suggested I can see that this is actually a wl-paste issue.

```
wl-paste | cat -A          
 might be using the rust version of wl-clipboard (I cant recall if I had moved off from it)^M$
^M$
https://github.com/YaLTeR/wl-clipboard-rs^M$
^M$
EDIT: Comparing the version I have and what is on github, it seems likely that I am.^M$
^M$
```

Thanks for helping me debug this. Will try and figure it out from `wl-clipboard`s side. You mentioned that you use `xclip` - are you running in wayland as I was not aware that this works there.

**Comment by blueyed** [comment]
I'm not using Wayland.

I think Neovim could / should maybe actually handle this, e.g. by normalizing/removing trailing `\r` (if it turns out to be expected behavior with wl-clipboard itself).

**Comment by MichaelAquilina** [comment]
I'm asking other wayland users with neovim to see if they have my same issue on their distribution.

**Comment by MichaelAquilina** [comment]
Asked a friend to test this out. He has the same issue when copying from firefox/gedit like I tested.

When we tried copying text from chrome though it worked fine - so it seems like it might be an issue unrelated to neovim. Not sure if you have an opinion about this? Should neovim be string out the ^M in these scenarios?

**Comment by MichaelAquilina** [comment]
Some more information:
It seems like we only get this issue when copying from wayland applications (e.g. running firefox in wayland, gedit in wayland). Anything running in X does not copy text that then exhibits this issue.

**Comment by blueyed** [comment]
> Should neovim be string out the ^M in these scenarios?

IMHO yes - if it is consistent (every line has it).

**Comment by MichaelAquilina** [comment]
Re-opening the issue as it seems there is still some stuff left to discuss. Is there anything you would like to test to check how consistent this is so we could confident with stripping them out?

**Comment by bfredl** [comment]
Does the wayland protocol mandate that apps should add ^M before every linebreak in a text clipboard? Or is this something that wl-clipboard utility does?

**Comment by MichaelAquilina** [comment]
> Does the wayland protocol mandate that apps should add ^M before every linebreak in a text clipboard? Or is this something that wl-clipboard utility does?

I'm not sure, I'd have to look into some docs. But it feels like a strange requirement considering carriage returns are mostly used on windows machines.

**Comment by bfredl** [comment]
wl-paste doesn't seem to do any data munging, expect for added final newline, which we already have turned off. https://github.com/bugaevc/wl-clipboard/blob/master/src/wl-paste.c#L198

**Comment by MichaelAquilina** [comment]
so this seems to imply that the waylanf apps themselves have the `^M` in place

**Comment by bfredl** [comment]
Not sure why. The specification doesn't seem to say anything about it. Maybe one could look into e.g. the GTK wayland implementation for hints.

**Comment by justinmk** [comment]
> Interestingly, pasting directly from the terminal by entering insert mode and then pasting using shift+ctrl+v pastes the content correctly.

In that case it is handled by bracketed paste. 

I don't see how we can know whether an incoming paste should be "scrubbed" of undesirable characters.

**Comment by NicholasAsimov** [comment]
@MichaelAquilina did you figure it out? I think this is a GTK3 issue, I tried to copy from some Qt5 applications [`QT_QPA_PLATFORM=wayland`] (browser Falkon, text editor FeatherPad) and they didn't have carriage returns. On the other hand GTK3 applications [`GDK_BACKEND=wayland`] (browser Eolie, text editor Geany) did have them.

**Comment by MichaelAquilina** [comment]
@NicholasAsimov I'm afraid not. I do think you are right however, this is probably a GTK3 on wayland issue.

**Comment by pat-s** [comment]
Just confirming the issue here on Sway. No issue with the same config on macOS.

**Comment by NicholasAsimov** [comment]
@MichaelAquilina @pat-s if someone is interested in a quick workaround while this is not fixed, here is a custom clipboard provider that trims carriage returns on paste. All commands match the current master ([runtime/autoload/provider/clipboard.vim](https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/clipboard.vim#L85)) except `wl-paste` command is piped to `tr`.

Add this to your vimrc:
```vim
" Wayland clipboard provider that strips carriage returns (GTK3 issue).
" This is needed because currently there's an issue where GTK3 applications on
" Wayland contain carriage returns at the end of the lines (this is a root
" issue that needs to be fixed).
let g:clipboard = {
      \   'name': 'wayland-strip-carriage',
      \   'copy': {
      \      '+': 'wl-copy --foreground --type text/plain',
      \      '*': 'wl-copy --foreground --type text/plain --primary',
      \    },
      \   'paste': {
      \      '+': {-> systemlist('wl-paste --no-newline | tr -d "\r"')},
      \      '*': {-> systemlist('wl-paste --no-newline --primary | tr -d "\r"')},
      \   },
      \   'cache_enabled': 1,
      \ }
```

**Comment by blueyed** [comment]
@NicholasAsimov 
Thanks!

Is there an upstream issue somewhere already?
It would be great to know if that's expected etc.

**Comment by justinmk** [comment]
Note that the bracketed paste handler for TUI (which is different than clipboard) already "scrubs" bytes implicitly: `tui.c:tk_getkeys()` calls libtermkeys' `tk_getkey` which translates various bytes (and there does not seem to be a way to avoid this).

**Comment by NicholasAsimov** [comment]
@justinmk your latest patch doesn't affect normal mode pasting (`"+p`), right? The literal CR (`^M`) chars are still pasted?

**Comment by NicholasAsimov** [comment]
@blueyed Someone left a bug report for Firefox regarding CRLF markers, but honestly I'm not sure it's upstream enough. I think GTK3 should use LF marker for line breaks on Linux because QT5 applications don't have this problem.

Interesting issue to be honest. It's either a design choice by GTK or a bug.

https://bugzilla.mozilla.org/show_bug.cgi?id=1572104

**Comment by justinmk** [comment]
> @justinmk your latest patch doesn't affect normal mode pasting (`"+p`), right? The literal CR (`^M`) chars are still pasted?

9f81acc doesn't affect `"+` at all. `"+` is clipboard, not "paste" (see `:help paste`). 

I marked this issue as "related" because the symptoms are similar.

**Comment by edrex** [comment]
https://gitlab.gnome.org/GNOME/gtk/issues/2307

**Comment by b0o** [comment]
To add to @NicholasAsimov's workaround, you may only want to remove carriage returns if they occur before a newline:

```vim
" Wayland clipboard provider that strips carriage returns (GTK3 issue).
" This is needed because currently there's an issue where GTK3 applications on
" Wayland contain carriage returns at the end of the lines (this is a root
" issue that needs to be fixed).
let g:clipboard = {
      \   'name': 'wayland-strip-carriage',
      \   'copy': {
      \      '+': 'wl-copy --foreground --type text/plain',
      \      '*': 'wl-copy --foreground --type text/plain --primary',
      \    },
      \   'paste': {
      \      '+': {-> systemlist('wl-paste --no-newline | sed -e "s/\r$//"')},
      \      '*': {-> systemlist('wl-paste --no-newline --primary | sed -e "s/\r$//"')},
      \   },
      \   'cache_enabled': 1,
      \ }

```

**Comment by jounathaen** [comment]
I used @b0o / @NicholasAsimov's   workarounds here, but with both of them I had problems with a different pasting behaviour. So I asked on stackexchange and got the valuable answer, to add two more arguments to the `systemlist`: https://vi.stackexchange.com/questions/26895/custom-gclipboard-results-in-p-always-pasting-into-the-same-line/26897

So this is my g:clipboard now:

```vim
if exists('$WAYLAND_DISPLAY')
    " clipboard on wayland with newline fix
    let g:clipboard = {
                \   'name': 'WL-Clipboard with ^M Trim',
                \   'copy': {
                \      '+': 'wl-copy --foreground --type text/plain',
                \      '*': 'wl-copy --foreground --type text/plain --primary',
                \    },
                \   'paste': {
                \      '+': {-> systemlist('wl-paste --no-newline | sed -e "s/\r$//"', '', 1)},
                \      '*': {-> systemlist('wl-paste --no-newline --primary | sed -e "s/\r$//"', '', 1)},
                \   },
                \   'cache_enabled': 1,
                \ }
endif
```

**Comment by tombh** [comment]
Thanks for these snippets everyone. Just wanted add that these also appear to fix an issue I had where I couldn't copy anything from outside vim that begun with a `--`, I'd got into the habit of always trying to include a space in my selection, so I'd copy ` --`. But now this is fixed. I have normal copy pasting again!

**Comment by 0x7D2B** [comment]
Here is a version of the clipboard provider which will only paste plain text, giving **E353: Nothing in register** if non-text content is in the clipboard. This will prevent any binary content from being damaged by the newline fix.

```viml
if exists('$WAYLAND_DISPLAY')
    " clipboard on wayland with newline fix
    let g:clipboard = {
        \   'name': 'WL-Clipboard with ^M Trim',
        \   'copy': {
        \      '+': 'wl-copy --foreground --type text/plain',
        \      '*': 'wl-copy --foreground --type text/plain --primary',
        \    },
        \   'paste': {
        \      '+': {-> systemlist('wl-paste --no-newline --type "text/plain;charset=utf-8" 2>/dev/null | sed -e "s/\r$//"', '', 1)},
        \      '*': {-> systemlist('wl-paste --no-newline --type "text/plain;charset=utf-8" --primary 2>/dev/null | sed -e "s/\r$//"', '', 1)},
        \   },
        \   'cache_enabled': 1,
        \ }
endif
```

**Comment by b0o** [comment]
A [fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1547595#c46) for this issue was included in Firefox 81. Not sure about other GTK apps. I've happily removed the clipboard workaround from my vimrc because it was messing with pasting after yanking in visual block mode.

**Comment by mvz** [comment]
@justinmk was this actually fixed for pasting using `wl-paste`? I'm still seeing this problem.

**Comment by YusufGandhi** [comment]
I have got the same issue when pasting using `p` command from a Microsoft Excel cell to Neovim. I got `^M` at the end of each line. However, pasting the same content to Vim 8.0, it was pasted normally.  

I am on the following version of NVIM:
```
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/build/config -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/src -I/usr/local/include -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/build/include
Compiled by brew@BigSur
```

**Comment by brycepg** [comment]
I'm running this issue using Windows Subsystem for Linux. My current workaround is this command in my vimrc:

    command! Slinefeed :%s/\r//

:Slinefeed

**Comment by tartley** [comment]
FWIW I'm still seeing this today, on Ubuntu 22.04, when pasting from gnome-terminal.

**Comment by nullbio** [comment]
I'm on WSL2, no wl-clipboard, have xclip installed. Whenever I paste in normal mode I get the ^M on every line. If I go edit mode first then paste I don't.

**Comment by dinhlongviolin1** [comment]
same issue here with same setup as @nullbio

**Comment by tchiadeu** [comment]
@nullbio Don't know if you still have the issue.

For me, it happened when I add the possibility to copy to clipboard for pasting code outside of neovim.
So, I checked in command mode help for clipboard running `:help clipboard`
Reading the informations, you can find this :
`							      *clipboard-wsl*
For Windows WSL, try this g:clipboard definition:
>vim
    let g:clipboard = {
                \   'name': 'WslClipboard',
                \   'copy': {
                \      '+': 'clip.exe',
                \      '*': 'clip.exe',
                \    },
                \   'paste': {
                \      '+': 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
                \      '*': 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
                \   },
                \   'cache_enabled': 0,
                \ }
`

I use this, with a modification to match the lua language :
`vim.g.clipboard = {
  name = "WslClipboard",
  copy = {
    ["+"] = "clip.exe",
    ["*"] = "clip.exe",
  },
  paste = {
    ["+"] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
    ["*"] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
  },
  cache_enabled = 0,
}
`

It worked for me.
