### ISSUE TITLE
TUI: bg color response consumed as user input (inserts "g", "0000/2b2b/3636^G")

### ISSUE THREAD

**Issue by adamtabrams** [neovim/neovim#11393]
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: macOS Majave 10.14.6
- Terminal name/version: Alacritty 0.3.3 (also with iTerm 3.2.7)
- `$TERM`: xterm-256color (also with `$TERM`: alacritty)

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```
I cannot reproduce this 100% of the time. Often, when I open a file (even with nvim -u NORC file.txt), the first character of the file is replaced with g and then the command-line shows :0000/2b2b/3636^G. Sometimes the first letter isn't changed and only the command-line shows /3636.

The problem happens more often when I open nvim from [lf](https://github.com/gokcehan/lf). It seems like this may have to do with terminal colors. It also appears that [this](https://github.com/neovim/neovim/issues/11062) and [this](https://github.com/neovim/neovim/issues/9991) issue might somehow be related. 

The behavior that I'm seeing is the same as if I entered these characters after startup from normal mode: ``` ^[]11;rgb:0000/2b2b/3636^G ``` 
That string is what my terminal outputs when I execute ```echo -e "\e]11;?\a"``` or ```printf '\e]11;?\007'; read``` which I've read are sometimes used to check background colors.

### Actual behaviour
Nvim opens a file and often changes the first character to g and starts entering a command as if from one types ```:0000/2b2b/3636^G``` from normal mode.

### Expected behaviour
Nvim opens a file, doesn't change the buffer contents, and is in normal mode.

**Comment by justinmk** [comment]
Maybe regressed by https://github.com/neovim/neovim/commit/8a4ae3d664a22cfaa3ec05635d26a8d662458c7e and/or https://github.com/neovim/neovim/commit/f96d1e6bc416fe0d1d11321234637695ff0e514e . 

- Can you try the development version? The [Releases](https://github.com/neovim/neovim/releases) page has a zip for macOS. 
- Can you try building https://github.com/neovim/neovim/commit/7e46fcaf2307c8ea409f32459bd9fb4f1ae44b7b (which is before those commits) and see if the problem happens there. Then try the other commits, and see if it happens there.

```
rm -rf build .deps
git checkout 7e46fcaf2307c8
make
./build/bin/nvim
```

**Comment by aoi1** [comment]
I think I have the same problem.(inserts "g", "16/17/1e^G" for me)
- I tried using NVIM v0.5.0-175-g525bb1b55 but it happens.
- I build 7e46fca and opened neovim, and it still happens.

I would try other commits and see if it happens.

**Comment by justinmk** [comment]
@aoi1 thanks, that is very helpful. Try going back to tag `v0.3.8` (edad3608009f69ed887c534f655fb02ab4e8fc44):

```
rm -rf build .deps
git checkout edad3608009
make
./build/bin/nvim
```

(note: make sure to run `./build/bin/nvim`, not `nvim`)

Then if it doesn't happen there, try "bisecting" using `git bisect`.

```
git checkout 7e46fcaf2307c8
git bisect start
git bisect bad
git checkout edad3608009
git bisect good
# git chooses the next commit for you, then you:
rm -rf build .deps
make
./build/bin/nvim
git bisect bad  # or "git bisect good"
# git chooses the next commit for you, repeat ...
```

**Comment by adamtabrams** [comment]
@justinmk I tried the latest version, the problem still occurred with that. Same with 7e46fcaf2307c8. So far, I have not been able to reproduce the problem with edad3608009.

**Comment by justinmk** [comment]
Great, so can you continue bisecting

**Comment by pfranz** [comment]
There were a few commits I couldn't build like complaints about no appimage target (I'm building the appimage).

```
[vagrant@localhost neovim]$ git bisect skip
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
298608f88c463705cfd6ee47035c049dbb1d9fa0
5372d9a705b849459bcb5ed52823fa422d0745de
7e9b99d55be68938689b9f593e200054533c3783
We cannot bisect more!
```

**Comment by justinmk** [comment]
@pfranz Thanks. So this is just simply a result of bg color detection, not a regression since then. BTW what terminal are you using?

**Comment by pfranz** [comment]
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

That ships with CentOS 7.6

**Comment by justinmk** [comment]
@pfranz bash is the shell inside the terminal. Need to know the GUI application you are running in--that is the terminal.

**Comment by pfranz** [comment]
macOS Catalina Terminal sshed in. I don’t have the issue locally in macOS or when sshed into a Cent 7.6 local vm.

**Comment by pfranz** [comment]
macOS Terminal 2.10 (433) and iTerm2 3.3.7 are affected for me.  The code seems to be related to my background, like you mentioned.  With the Basic theme it's ffff/ffff/ffff^G and another it's 00/00/00^G.

When logged into that workstation Konsole, Mate Terminal, and xterm are not affected.

**Comment by adamtabrams** [comment]
@justinmk I finished bisecting. And I was able to build all of them. I got this as a result:
```
298608f88c463705cfd6ee47035c049dbb1d9fa0 is the first bad commit
commit 298608f88c463705cfd6ee47035c049dbb1d9fa0
Author: Josh Triplett <josh@joshtriplett.org>
Date:   Tue Jul 12 22:52:10 2016 -0700

    Automatically detect terminal background and set bg=dark or bg=light

    xterm-compatible terminals support reporting their configured colors
    back to the application.  Use this to obtain the current background
    color, compute its luminance to classify it as light or dark, and set
    'bg' accordingly.  Also set the default for 'bg', so that `:set bg&`
    will revert to that detected default.

:040000 040000 73f0ee11d2ef25dcf0031a59408f0218fbaa9962 765cb4d80635e7a6778ebe23d5cb53cbef6b9564 M	src
```

I can also post the bisect log if that is helpful?

P.S. Some builds required ```make SDKROOT=`xcrun --show-sdk-path` MACOSX_DEPLOYMENT_TARGET=``` and a couple required me to manually run ```./luarocks install luacheck``` after make failed.

**Comment by blueyed** [comment]
I wonder if this fixes it (for master):
```diff
diff --git i/src/nvim/tui/input.c w/src/nvim/tui/input.c
index c71378463..7459fa42c 100644
--- i/src/nvim/tui/input.c
+++ w/src/nvim/tui/input.c
@@ -444,9 +444,9 @@ static void set_bg_deferred(void **argv)
 // [1] https://en.wikipedia.org/wiki/Luma_%28video%29
 static bool handle_background_color(TermInput *input)
 {
-  if (input->waiting_for_bg_response <= 0) {
-    return false;
-  }
   size_t count = 0;
   size_t component = 0;
   size_t header_size = 0;
```
Also, what does this display in your terminal?  `printf '\x1b]11;?\x07'; sleep 1`
With Kitty I get:  `^[]11;rgb:fdfd/f6f6/e3e3^[\`.
Maybe the response from your terminal(s) is not handled in `handle_background_color`?

**Comment by adamtabrams** [comment]
@blueyed I tried ```printf '\x1b]11;?\x07'; sleep 1``` for various terminals and got the following.
Alacritty returns: ```^[]11;rgb:0000/2b2b/3636^G```
iTerm2 returns: ```^[]11;rgb:00/2b/36^G```
Terminal.app returns nothing.
But most of my testing for this issue has been with Alacritty.

**Comment by blueyed** [comment]
@adamtabrams 
Thanks - I've seen now that you've mentioned this in your original comment already.
Do you see it (the issue) only in Alacritty or iTerm2 also?
Given that you've said it might be related to terminal colors etc, I wonder if there are many other responses/things then, so that Neovim stops handling the background color.
Can you try the patch from my previous comment?

**Comment by aoi1** [comment]
For me, I always use iTerm2 and get this issue.
I try to try the patch, but I couldn't find the code in my master branch🤔
```
 if (input->waiting_for_bg_response <= 0) {
    return false;
}
```

**Comment by blueyed** [comment]
@aoi1 
Yes, the code is new (not in 0.4), so maybe it is fixed in master already.
Please ensure that "your master branch" is the actual master, i.e. pull it etc.  You can ask for help on IRC/Gitter.

**Comment by aoi1** [comment]
@blueyed Okay, I misunderstood. So I tried the command below at master branch, but it doesn't seem to be fixed😢 I've attached the snapshot.
```
git checkout master
git pull
rm -rf build .deps
make
./build/bin/nvim
```
![Uploading スクリーンショット 2019-12-06 12.56.38.png…]()

**Comment by blueyed** [comment]
@aoi1 
ok.  Can you try the patch from https://github.com/neovim/neovim/issues/11393#issuecomment-561586318 then, please?

**Comment by adamtabrams** [comment]
@blueyed I switched to the most up-to-date master, and the problem still occurred. Then, I applied the patch you recommended, and the problem continued.

**Comment by aoi1** [comment]
@blueyed Same as @adamtabrams, I applied the patch, and the problem continued.

**Comment by adamtabrams** [comment]
@blueyed @justinmk Why does neovim try to automatically detect and set bg to dark or light. Isn't that already a setting that a user can manipulate themself?

**Comment by blueyed** [comment]
@adamtabrams see #5027
I've given "asking for bg only if not set manually already" a try in https://github.com/neovim/neovim/pull/11579.

**Comment by jpribyl** [comment]
Has there been any progress on this? I built the branch in https://github.com/neovim/neovim/pull/11579 from source but still seem to have the issue in iterm2 😞

**Comment by adamtabrams** [comment]
@jpribyl do you have `set background=dark` or `set background=light` in your init.vim (or vimrc)?

**Comment by dm1try** [comment]
@jpribyl please, try #12004 , it looks promising :)

**Comment by jpribyl** [comment]
@adamtabrams I do have `set background=dark`
@dm1try thank you I will look at it!

One interesting thing I noticed is that the issue never seems to occur while in a `tmux` session.. so another possible workaround might also be to start tmux from my `.bash_profile`

**Comment by Cupprum** [comment]
Soooo did you guys find some fix for this? cause `set background=dark` doesnt work for me and i dont understand #12004

**Comment by jpribyl** [comment]
@Cupprum I just edited my configs to always use `tmux` and avoid the issue that way 🤷 none of the other solutions worked for me. Good luck, you should post if you discover anything useful!

**Comment by Cupprum** [comment]
@jpribyl well but thats kind of nasty fix :D

**Comment by jpribyl** [comment]
@Cupprum completely agree! It's just a band-aid in the hopes that eventually some update will be merged which fixes the root issue. I would love for a better solution but I don't have time to investigate this any more right now!

**Comment by adamtabrams** [comment]
Here's the "band-aid" I've been using: `cnoremap 3636  <c-u>undo<CR>`

**Comment by adamtabrams** [comment]
Just starting using version 0.4.4! Just wanted to document that the bug still happens for me.

**Comment by Cupprum** [comment]
I have done some research. It doesn't seem like neovim's fault. Something similar happens in normal vim as well. When i open it, in the bottom left part i can see some strange characters. I guess it has something to do with terminal and is only present on mac os. I personally use iterm2. In normal apple terminal this issue occurred several times as well. In my opinion it has something to do with colours.

**Comment by adamtabrams** [comment]
@Cupprum As mentioned earlier in this thread, the characters appear because Neovim is trying to `Automatically detect terminal background and set bg=dark or bg=light`
You can find more about this in commit 298608f88c463705cfd6ee47035c049dbb1d9fa0.

The problem is that some terminals don't react to this as intended. @blueyed came up with great solution: if `bg` is already set in the user config, Neovim shouldn't try to automatically detect and set it.

Just to clarify, this behavior should be fixed by Neovim (not by every terminal that Neovim might be run in). A feature was implemented. It doesn't work as intended for all cases. So there should at least be a way to disable that feature when it isn't working properly.

**Comment by jamessan** [comment]
> @blueyed came up with great solution: if `bg` is already set in the user config, Neovim shouldn't try to automatically detect and set it.

No, that's a band-aid.  #12004 looks like the more appropriate fix.  Can people experiencing this bug confirm whether that fixes the issue?

**Comment by adamtabrams** [comment]
@jamessan I tried out #12004 and was not able to reproduce the bug while using it!

**Comment by iamjesper** [comment]
@jamessan echoing the comment above, https://github.com/neovim/neovim/pull/12004 also fixes the issue for me.

**Comment by ecerulm** [comment]
nvim 4.4.0 still has the problem (current stable release in May 2021) and you will need to install 0.5.0-dev or later to get rid of this problem

**Comment by thallium** [comment]
Still have this problem on neovim 0.5, but only happens when two terminal attach to the same tmux session.

**Comment by jmahlik** [comment]
Not sure if this helps but I get this issue on windows using git bash/msys2 and entering `nvim`. I switched to windows terminal, still using git's `bash.exe` as the shell and the issue is not there when using windows terminal.
