### ISSUE TITLE
Segment fault when using :terminal

### ISSUE THREAD

**Issue by lourenci** [neovim/neovim#11548]
I'm having segment fault errors after selecting some item with fzf. Has anyone experimented any problem with it too?

![image](https://user-images.githubusercontent.com/2339362/70710133-4f1e3d80-1cbd-11ea-91e3-36721671511e.png)

I don't know neither how to reproduce nor how to get some stack trace for debug as this error happens every now and then without any pattern, just after selecting some item from the fzf list. Can someone help me with that? 

My currently configs:
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: MacOS 10.15.2
- Terminal name/version: Iterm 3.3.7
- `$TERM`: xterm-256color
- Fzf.vim plugin from master

**Comment by jdhao** [comment]
You may give [leaderf](https://github.com/Yggdroot/LeaderF) a try. It is a good fuzzy find plugin with floating window support.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/wiki/FAQ#backtrace-macos--osx

**Comment by lourenci** [comment]
```
Process:               nvim [95167]
Path:                  /usr/local/Cellar/neovim/0.4.3/bin/nvim
Identifier:            nvim
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        zsh [94922]
Responsible:           iTerm2 [94918]
User ID:               501

Date/Time:             2019-12-13 16:52:35.176 -0300
OS Version:            Mac OS X 10.15.2 (19C57)
Report Version:        12
Anonymous UUID:        6E17421F-3666-46D6-1BE8-65FA24485E18

Sleep/Wake UUID:       471252D3-D19F-4635-9AAB-BFDD4B94EA4C

Time Awake Since Boot: 94000 seconds
Time Since Wake:       30000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007ffee2a5ea6c
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [95167]

VM Regions Near 0x7ffee2a5ea6c:
    Stack                  00007ffee225d000-00007ffee2a5d000 [ 8192K] rw-/rwx SM=ALI  thread 0
--> 
    Submap                 00007fff00000000-00007fff80000000 [  2.0G] r--/rwx SM=SHM  machine-wide VM submap

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   nvim                          	0x000000010d338449 win_line + 21675
1   nvim                          	0x000000010d32db8f win_update + 4629
2   nvim                          	0x000000010d32b75f update_screen + 1990
3   nvim                          	0x000000010d38369b terminal_check.llvm.1248222012857778337 + 43
4   nvim                          	0x000000010d36c610 state_enter + 40
5   nvim                          	0x000000010d3825dd terminal_enter + 311
6   nvim                          	0x000000010d1f71ca edit + 118
7   nvim                          	0x000000010d2d6c85 normal_execute.llvm.14737442407928562592 + 2474
8   nvim                          	0x000000010d36c6ac state_enter + 196
9   nvim                          	0x000000010d2ab89d main + 10367
10  libdyld.dylib                 	0x00007fff701987fd start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff70398818 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff70398818 start_wqthread + 0

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff702ddbce kevent + 10
1   libuv.1.dylib                 	0x000000010d4cb926 uv__io_poll + 854
2   libuv.1.dylib                 	0x000000010d4bd1e2 uv_run + 359
3   nvim                          	0x000000010d240106 loop_poll_events + 138
4   nvim                          	0x000000010d387325 tui_main.llvm.4175664286289804232 + 914
5   libsystem_pthread.dylib       	0x00007fff7039ce65 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff7039883b thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007f8d3a01f400  rbx: 0x00007f8d39603260  rcx: 0x0000000000000004  rdx: 0x0000000000000004
  rdi: 0x0000000000000074  rsi: 0x00007ffee2a5ea6c  rbp: 0x00007ffee2a5bfd0  rsp: 0x00007ffee2a5ab50
   r8: 0x0000000000000004   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000005
  r12: 0x00007f8d3a00de00  r13: 0x0000000000000000  r14: 0x0000000000000001  r15: 0x0000000000000f23
  rip: 0x000000010d338449  rfl: 0x0000000000010206  cr2: 0x00007ffee2a5ea6c
  
Logical CPU:     3
Error Code:      0x00000004 (no mapping for user data write)
Trap Number:     14


Binary Images:
       0x10d1a3000 -        0x10d3f8fff +nvim (0) <11FC2FCA-C51E-3D10-A273-41E5D2CCC6DC> /usr/local/bin/nvim
       0x10d4a7000 -        0x10d4afffb +libintl.8.dylib (0) <9E94108B-5714-3275-90C8-EBE92F56C0CE> /usr/local/opt/gettext/lib/libintl.8.dylib
       0x10d4b7000 -        0x10d4d0ff3 +libuv.1.dylib (0) <487BDF6A-1560-311A-8E07-84AD3AFEB9C3> /usr/local/opt/libuv/lib/libuv.1.dylib
       0x10d4e5000 -        0x10d4e9fff +libmsgpackc.2.dylib (0) <47D393D6-231E-3259-80D4-0D44C1B821D5> /usr/local/opt/msgpack/lib/libmsgpackc.2.dylib
       0x10d4ed000 -        0x10d4f6fff +libvterm.0.dylib (0) <302F2388-F616-3EEC-ADB0-8A7E19580B02> /usr/local/opt/libvterm/lib/libvterm.0.dylib
       0x10d500000 -        0x10d505fff +libtermkey.1.dylib (0) <BF173A8F-189B-36FE-883B-C2122522721B> /usr/local/opt/libtermkey/lib/libtermkey.1.dylib
       0x10d510000 -        0x10d517ff3 +libunibilium.4.dylib (0) <5AB114C3-3FAF-37CC-AF9B-0222C0EFB2E8> /usr/local/opt/unibilium/lib/libunibilium.4.dylib
       0x10d521000 -        0x10d5a7ff7 +libluajit-5.1.2.dylib (0) <4ABE53ED-73E8-385C-9BA6-712D50F85A16> /usr/local/opt/luajit/lib/libluajit-5.1.2.dylib
       0x11c06b000 -        0x11c0fbcb7  dyld (733.8) <EEA931D0-403E-3BC8-862A-CBA037DE4A74> /usr/lib/dyld
    0x7fff38ab9000 -     0x7fff38f39fe7  com.apple.CoreFoundation (6.9 - 1674.103) <D1F93A5F-5FB9-3088-BC16-36DBF58144C0> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff6caff000 -     0x7fff6cb01ff7  libDiagnosticMessagesClient.dylib (112) <D84AA565-8B5C-39EB-AB5E-61DC38B8493C> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff6cfc7000 -     0x7fff6cfc8ff3  libSystem.B.dylib (1281) <2F6BCFD9-A5F9-30FE-BF5A-5C53D3CBAB4D> /usr/lib/libSystem.B.dylib
    0x7fff6d2ad000 -     0x7fff6d300ff7  libc++.1.dylib (800.7) <6018A70E-5CD3-32AF-BA60-E7A0B7E7CEB2> /usr/lib/libc++.1.dylib
    0x7fff6d301000 -     0x7fff6d315fff  libc++abi.dylib (800.7) <BC1E5821-4540-3226-ABB0-BC35E4DDF0B9> /usr/lib/libc++abi.dylib
    0x7fff6d316000 -     0x7fff6d316ffb  libcharset.1.dylib (59) <1B71DC8A-FBF2-37F8-92C0-34AE72B7CED3> /usr/lib/libcharset.1.dylib
    0x7fff6dd79000 -     0x7fff6dd7bfff  libfakelink.dylib (149) <AAA5BBB4-F6FA-3B36-9245-B6999A95C63C> /usr/lib/libfakelink.dylib
    0x7fff6dd9a000 -     0x7fff6de8aff7  libiconv.2.dylib (59) <54B90704-F9C8-31B4-AE04-FE496B3725A3> /usr/lib/libiconv.2.dylib
    0x7fff6de8b000 -     0x7fff6e0e3ff7  libicucore.A.dylib (64252.0.1) <AD2FDFC2-F9D9-3D64-950A-6CF6FC114B95> /usr/lib/libicucore.A.dylib
    0x7fff6ee18000 -     0x7fff6ee49fc6  libobjc.A.dylib (781.2) <17241F77-6A7A-39D7-8836-63E2725AA3C9> /usr/lib/libobjc.A.dylib
    0x7fff6f3ce000 -     0x7fff6f3d1ffb  libutil.dylib (57) <86C9C769-0523-38C6-940E-900C8CAB780A> /usr/lib/libutil.dylib
    0x7fff6f4f4000 -     0x7fff6f506ffb  libz.1.dylib (76) <1005ADEB-04A2-3E42-B915-AB4B40A7AB3A> /usr/lib/libz.1.dylib
    0x7fff6ff6a000 -     0x7fff6ff6fff3  libcache.dylib (83) <AD7479C0-73FA-3B2E-9544-D566DFFAB4C6> /usr/lib/system/libcache.dylib
    0x7fff6ff70000 -     0x7fff6ff7bfff  libcommonCrypto.dylib (60165) <F7B65873-FAC8-3EB5-8912-34109EFC74B5> /usr/lib/system/libcommonCrypto.dylib
    0x7fff6ff7c000 -     0x7fff6ff83fff  libcompiler_rt.dylib (101.2) <51107CAA-0727-370D-8287-940D40D09AC1> /usr/lib/system/libcompiler_rt.dylib
    0x7fff6ff84000 -     0x7fff6ff8dfff  libcopyfile.dylib (166.40.1) <6454A046-88E5-32D6-898C-FB0D30D28637> /usr/lib/system/libcopyfile.dylib
    0x7fff6ff8e000 -     0x7fff70025fe7  libcorecrypto.dylib (866.60.3) <8090C446-35C8-31B4-8B1E-AF6D0EF3524B> /usr/lib/system/libcorecrypto.dylib
    0x7fff7013c000 -     0x7fff7017dff0  libdispatch.dylib (1173.60.1) <A9EDFE95-31BA-3BEF-89CA-60DE153237FA> /usr/lib/system/libdispatch.dylib
    0x7fff7017e000 -     0x7fff701b3ff7  libdyld.dylib (733.8) <8E2D3DED-0756-37A0-9D55-B9264CA020B4> /usr/lib/system/libdyld.dylib
    0x7fff701b4000 -     0x7fff701b4ffb  libkeymgr.dylib (30) <0B9A3AF7-086E-3E7A-A52E-3DAF2E52CF86> /usr/lib/system/libkeymgr.dylib
    0x7fff701c2000 -     0x7fff701c2ff7  liblaunch.dylib (1738.61.1) <A061D971-A337-3528-8B78-FFAD2B0B5CC6> /usr/lib/system/liblaunch.dylib
    0x7fff701c3000 -     0x7fff701c8ff7  libmacho.dylib (949.0.1) <9831715F-ED86-3A9D-88CD-152C888B784B> /usr/lib/system/libmacho.dylib
    0x7fff701c9000 -     0x7fff701cbff7  libquarantine.dylib (110.40.3) <58CE8913-EC7B-376B-BC80-69763993A1E4> /usr/lib/system/libquarantine.dylib
    0x7fff701cc000 -     0x7fff701cdff7  libremovefile.dylib (48) <4E1AD797-3993-3E05-BB9B-B4E3038CE09C> /usr/lib/system/libremovefile.dylib
    0x7fff701ce000 -     0x7fff701e5fff  libsystem_asl.dylib (377.60.2) <2CD6CABE-F8D7-3CCA-A930-08F8AC356D30> /usr/lib/system/libsystem_asl.dylib
    0x7fff701e6000 -     0x7fff701e6fff  libsystem_blocks.dylib (74) <71A75F21-83AD-382F-95E4-4D6B77B4B9FE> /usr/lib/system/libsystem_blocks.dylib
    0x7fff701e7000 -     0x7fff7026eff7  libsystem_c.dylib (1353.60.8) <ECA8CD0D-0B55-3151-B389-8109DAEC85B1> /usr/lib/system/libsystem_c.dylib
    0x7fff7026f000 -     0x7fff70272ffb  libsystem_configuration.dylib (1061.40.2) <CE186284-4923-35DE-9141-7B6B89523668> /usr/lib/system/libsystem_configuration.dylib
    0x7fff70273000 -     0x7fff70276ff7  libsystem_coreservices.dylib (114) <FBE4483A-7B6E-30CF-AECE-828AFFACDC15> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff70277000 -     0x7fff7027ffff  libsystem_darwin.dylib (1353.60.8) <9AC37996-630C-3B1E-8285-CFC77B684359> /usr/lib/system/libsystem_darwin.dylib
    0x7fff70280000 -     0x7fff70287ffb  libsystem_dnssd.dylib (1096.60.2) <7F0DF910-F4AC-3CED-9494-295B5E45549C> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff70288000 -     0x7fff70289ffb  libsystem_featureflags.dylib (17) <985005B7-C0B3-3DCA-B064-6D34A0687212> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff7028a000 -     0x7fff702d7fff  libsystem_info.dylib (538) <D9805FBC-1BBD-3825-AB62-83C3ABB4191F> /usr/lib/system/libsystem_info.dylib
    0x7fff702d8000 -     0x7fff70304ff7  libsystem_kernel.dylib (6153.61.1) <90F8650F-D3A9-38B3-BB8C-B5D3686393BC> /usr/lib/system/libsystem_kernel.dylib
    0x7fff70305000 -     0x7fff7034cfcf  libsystem_m.dylib (3178) <92F1FF45-BD1C-32FE-A9A9-D12AF02C8212> /usr/lib/system/libsystem_m.dylib
    0x7fff7034d000 -     0x7fff70374fff  libsystem_malloc.dylib (283.60.1) <51472F42-71BE-348F-B42E-4EDD3040B690> /usr/lib/system/libsystem_malloc.dylib
    0x7fff70375000 -     0x7fff70382ffb  libsystem_networkextension.dylib (1095.60.2) <846C06C0-A705-38AE-8A29-3FA4153252B3> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff70383000 -     0x7fff7038cff3  libsystem_notify.dylib (241) <7CB7DE46-5877-3CAD-8526-CACEA22F3AD5> /usr/lib/system/libsystem_notify.dylib
    0x7fff7038d000 -     0x7fff70396fef  libsystem_platform.dylib (220) <AC9560A9-CCE8-3158-BCC8-8FF47929397A> /usr/lib/system/libsystem_platform.dylib
    0x7fff70397000 -     0x7fff703a1fff  libsystem_pthread.dylib (416.60.2) <9D14694F-F3FE-385D-9B23-6A87844D5CBF> /usr/lib/system/libsystem_pthread.dylib
    0x7fff703a2000 -     0x7fff703a6fff  libsystem_sandbox.dylib (1217.61.1) <AA2E4441-A517-3921-AF0E-AA8158D2A6D9> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff703a7000 -     0x7fff703a9fff  libsystem_secinit.dylib (62.60.1) <129C187A-E580-3F00-A0C3-E96A633364F1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff703aa000 -     0x7fff703b1ffb  libsystem_symptoms.dylib (1238.60.1) <5540DEA3-9C3A-3991-8C3A-7B375A5410C7> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff703b2000 -     0x7fff703c8ff2  libsystem_trace.dylib (1147.60.3) <EF6BD746-85CD-3490-92E6-7C7EDA0B703B> /usr/lib/system/libsystem_trace.dylib
    0x7fff703ca000 -     0x7fff703cfffb  libunwind.dylib (35.4) <769F4C16-2746-3182-85C1-45CC98D119C8> /usr/lib/system/libunwind.dylib
    0x7fff703d0000 -     0x7fff70404ffe  libxpc.dylib (1738.61.1) <AC9AD00D-BAA9-3ABC-B557-77E604CF9955> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1377350
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=369.8M resident=0K(0%) swapped_out_or_unallocated=369.8M(100%)
Writable regions: Total=66.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=66.2M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Dispatch continuations            8192K        1 
Kernel Alloc Once                    8K        1 
MALLOC                            40.3M       30 
MALLOC guard page                   16K        4 
MALLOC_LARGE (reserved)             80K        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        4 
Stack                             17.0M        4 
VM_ALLOCATE                        256K        2 
__DATA                            2207K       58 
__DATA_CONST                       192K        8 
__LINKEDIT                       354.1M       10 
__OBJC_RO                         32.0M        1 
__OBJC_RW                         1780K        2 
__TEXT                            15.7M       55 
__UNICODE                          564K        1 
mapped file                         28K        1 
shared memory                       48K        6 
===========                     =======  ======= 
TOTAL                            528.4M      190 
TOTAL, minus reserved VM space   528.4M      190 
```

**Comment by lourenci** [comment]
The problem is not with the fzf itself, it's happening when I start the `:terminal`. To reproduce:

* Set in your .vimrc the following `autocmd`:
```
  augroup StartTerminalInInsertMode
    " https://github.com/neovim/neovim/issues/8816
    autocmd!
    autocmd TermOpen term://* startinsert
  augroup END
```
* Write 4000 chars in the buffer and start the terminal (`4000ia<esc>:terminal`).

It will crash with segment fault.

**Comment by blueyed** [comment]
@lourenci 
With your example / test case it results in "E37: No write since last change (add ! to override)" with the final `:terminal`, and it does not crash with `:terminal!` / `:sp | terminal`.
Can you update your test case?  Are you using `nvim -u NONE`?

**Comment by lourenci** [comment]
Hi, @blueyed.

There is no problem at all when the command is `nvim -u NONE`. You need a minimum set of config to simulate that. Sorry for not making this clear in the message above.

To simulate that:

1. Set your `.vimrc` with the commands below:
```
set hidden
set nowrap

augroup StartTerminalInInsertMode
  " https://github.com/neovim/neovim/issues/8816
  autocmd!
  autocmd TermOpen term://* startinsert
augroup END
```

2. Start nvim with `nvim --noplugin`.
3. Write 4000 chars in the buffer and start the terminal (`4000ia<esc>:terminal`).

Even with the `StartTerminalInInsertMode` commented, I still have some issues with `fzf`. It's less frequent and I can't reproduce yet.

**Comment by lourenci** [comment]
It's happening in neovim's `HEAD`. Here is the backtrace:

```
Process:               nvim [42426]
Path:                  /usr/local/Cellar/neovim/HEAD-ead61e5/bin/nvim
Identifier:            nvim
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        zsh [18334]
Responsible:           iTerm2 [18330]
User ID:               501

Date/Time:             2020-02-05 10:13:35.207 -0300
OS Version:            Mac OS X 10.15.3 (19D76)
Report Version:        12
Anonymous UUID:        6E17421F-3666-46D6-1BE8-65FA24485E18

Sleep/Wake UUID:       4F06D54B-2A05-4785-A3A4-B5C251FA58EE

Time Awake Since Boot: 42000 seconds
Time Since Wake:       7800 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000002000004a1
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [42426]

VM Regions Near 0x2000004a1:
    __LINKEDIT             000000010e12a000-000000010e162000 [  224K] r--/r-- SM=COW  /usr/lib/dyld
--> 
    STACK GUARD            000070000a060000-000070000a061000 [    4K] ---/rwx SM=NUL  stack guard for thread 1

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   nvim                          	0x0000000107fa4d34 restore_chartab + 15
1   nvim                          	0x0000000107fa04c7 syn_current_attr.llvm.936487511375963985 + 2827
2   nvim                          	0x0000000107f9f91a get_syntax_attr + 192
3   nvim                          	0x0000000107fa11ff syn_get_id + 75
4   nvim                          	0x0000000107e41535 f_synID + 191
5   nvim                          	0x0000000107e2cf20 call_func + 3195
6   nvim                          	0x0000000107e2fb70 get_func_tv + 473
7   nvim                          	0x0000000107e3dfd7 eval7 + 4329
8   nvim                          	0x0000000107e3cc37 eval6 + 49
9   nvim                          	0x0000000107e3c7d5 eval5 + 53
10  nvim                          	0x0000000107e3c02d eval4 + 47
11  nvim                          	0x0000000107e3bebe eval3 + 48
12  nvim                          	0x0000000107e2ba90 eval1.llvm.12690911124660391743 + 50
13  nvim                          	0x0000000107e2fa59 get_func_tv + 194
14  nvim                          	0x0000000107e3dfd7 eval7 + 4329
15  nvim                          	0x0000000107e3cc37 eval6 + 49
16  nvim                          	0x0000000107e3c7d5 eval5 + 53
17  nvim                          	0x0000000107e3c02d eval4 + 47
18  nvim                          	0x0000000107e3bebe eval3 + 48
19  nvim                          	0x0000000107e2ba90 eval1.llvm.12690911124660391743 + 50
20  nvim                          	0x0000000107e3d84c eval7 + 2398
21  nvim                          	0x0000000107e3cc37 eval6 + 49
22  nvim                          	0x0000000107e3c7d5 eval5 + 53
23  nvim                          	0x0000000107e3c02d eval4 + 47
24  nvim                          	0x0000000107e3bebe eval3 + 48
25  nvim                          	0x0000000107e2ba90 eval1.llvm.12690911124660391743 + 50
26  nvim                          	0x0000000107e2b851 eval0 + 75
27  nvim                          	0x0000000107e38aca ex_return + 111
28  nvim                          	0x0000000107e7e293 do_one_cmd + 11902
29  nvim                          	0x0000000107e7a483 do_cmdline + 2561
30  nvim                          	0x0000000107e3590d ex_execute + 448
31  nvim                          	0x0000000107e7e293 do_one_cmd + 11902
32  nvim                          	0x0000000107e7a483 do_cmdline + 2561
33  nvim                          	0x0000000107e2d2ce call_func + 4137
34  nvim                          	0x0000000107e2fb70 get_func_tv + 473
35  nvim                          	0x0000000107e2f024 ex_call + 577
36  nvim                          	0x0000000107e7e293 do_one_cmd + 11902
37  nvim                          	0x0000000107e7a483 do_cmdline + 2561
38  nvim                          	0x0000000107e2d2ce call_func + 4137
39  nvim                          	0x0000000107e2fb70 get_func_tv + 473
40  nvim                          	0x0000000107e3dfd7 eval7 + 4329
41  nvim                          	0x0000000107e3cc37 eval6 + 49
42  nvim                          	0x0000000107e3c7d5 eval5 + 53
43  nvim                          	0x0000000107e3c02d eval4 + 47
44  nvim                          	0x0000000107e3bebe eval3 + 48
45  nvim                          	0x0000000107e2ba90 eval1.llvm.12690911124660391743 + 50
46  nvim                          	0x0000000107e2b851 eval0 + 75
47  nvim                          	0x0000000107e38aca ex_return + 111
48  nvim                          	0x0000000107e7e293 do_one_cmd + 11902
49  nvim                          	0x0000000107e7a483 do_cmdline + 2561
50  nvim                          	0x0000000107e2d2ce call_func + 4137
51  nvim                          	0x0000000107e2fb70 get_func_tv + 473
52  nvim                          	0x0000000107e3dfd7 eval7 + 4329
53  nvim                          	0x0000000107e3cc37 eval6 + 49
54  nvim                          	0x0000000107e3c7d5 eval5 + 53
55  nvim                          	0x0000000107e3c02d eval4 + 47
56  nvim                          	0x0000000107e3bebe eval3 + 48
57  nvim                          	0x0000000107e2ba90 eval1.llvm.12690911124660391743 + 50
58  nvim                          	0x0000000107e2b851 eval0 + 75
59  nvim                          	0x0000000107e2dd07 ex_let_const + 485
60  nvim                          	0x0000000107e7e293 do_one_cmd + 11902
61  nvim                          	0x0000000107e7a483 do_cmdline + 2561
62  nvim                          	0x0000000107e2d2ce call_func + 4137
63  nvim                          	0x0000000107e2fb70 get_func_tv + 473
64  nvim                          	0x0000000107e2f024 ex_call + 577
65  nvim                          	0x0000000107e7e293 do_one_cmd + 11902
66  nvim                          	0x0000000107e7a483 do_cmdline + 2561
67  nvim                          	0x0000000107eaa9e6 apply_autocmds_group.llvm.12490016584824525962 + 1660
68  nvim                          	0x0000000107fd9d2b close_last_window_tabpage + 393
69  nvim                          	0x0000000107fd42b3 win_close + 316
70  nvim                          	0x0000000107e7e293 do_one_cmd + 11902
71  nvim                          	0x0000000107e7a483 do_cmdline + 2561
72  nvim                          	0x0000000107e2d2ce call_func + 4137
73  nvim                          	0x0000000107e343de callback_call + 161
74  nvim                          	0x0000000107e0e5ac channel_callback_call + 290
75  nvim                          	0x0000000107e0efb6 on_channel_event + 94
76  nvim                          	0x0000000107e64561 multiqueue_process_events + 75
77  nvim                          	0x0000000107fb298d terminal_execute.llvm.6517004081443246748 + 723
78  nvim                          	0x0000000107f9bc3c state_enter + 196
79  nvim                          	0x0000000107fb24ad terminal_enter + 311
80  nvim                          	0x0000000107e19b3e edit + 118
81  nvim                          	0x0000000107f03d5e normal_execute.llvm.7192790989257211469 + 2474
82  nvim                          	0x0000000107f9bc3c state_enter + 196
83  nvim                          	0x0000000107ed509a main + 10382
84  libdyld.dylib                 	0x00007fff6ca107fd start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff6cc10818 start_wqthread + 0

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff6cb55bce kevent + 10
1   libuv.1.dylib                 	0x000000010811f75d uv__io_poll + 854
2   libuv.1.dylib                 	0x0000000108110a1e uv_run + 359
3   nvim                          	0x0000000107e63c7a loop_poll_events + 138
4   nvim                          	0x0000000107fb71ba tui_main.llvm.5994906605990800168 + 780
5   libsystem_pthread.dylib       	0x00007fff6cc14e65 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6cc1083b thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000200000001  rbx: 0x0000000000000000  rcx: 0x000000007fffffff  rdx: 0x000000007fffffff
  rdi: 0x00007ffee7e32880  rsi: 0x0000000000000000  rbp: 0x00007ffee7e32780  rsp: 0x00007ffee7e32780
   r8: 0x0000000000000018   r9: 0x0000000000000000  r10: 0x0000000000000005  r11: 0x0000001abacaf165
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000008cde000  r15: 0x0000000008cde000
  rip: 0x0000000107fa4d34  rfl: 0x0000000000010246  cr2: 0x00000002000004a1
  
Logical CPU:     2
Error Code:      0x00000004 (no mapping for user data write)
Trap Number:     14


Binary Images:
       0x107dc3000 -        0x108041fff +nvim (0) <DBE127F9-0883-3836-9094-FEBD6AFEED53> /usr/local/bin/nvim
       0x1080fa000 -        0x108102ffb +libintl.8.dylib (0) <9E94108B-5714-3275-90C8-EBE92F56C0CE> /usr/local/opt/gettext/lib/libintl.8.dylib
       0x10810a000 -        0x108124fff +libuv.1.dylib (0) <02E5BA21-9D05-3C31-939F-C833AA972E0E> /usr/local/opt/libuv/lib/libuv.1.dylib
       0x108138000 -        0x10813cfff +libmsgpackc.2.dylib (0) <95D0DF84-FB88-35A3-BEE3-6D4A97BE7E41> /usr/local/opt/msgpack/lib/libmsgpackc.2.dylib
       0x108142000 -        0x10814bfff +libvterm.0.dylib (0) <3AE119C9-C591-3179-9D7B-34E2A85ED00C> /usr/local/opt/libvterm/lib/libvterm.0.dylib
       0x108152000 -        0x108157fff +libtermkey.1.dylib (0) <BF173A8F-189B-36FE-883B-C2122522721B> /usr/local/opt/libtermkey/lib/libtermkey.1.dylib
       0x10815f000 -        0x108166ff3 +libunibilium.4.dylib (0) <5AB114C3-3FAF-37CC-AF9B-0222C0EFB2E8> /usr/local/opt/unibilium/lib/libunibilium.4.dylib
       0x10816f000 -        0x1081b7ff7 +libutf8proc.2.dylib (0) <E0AC7260-D063-3FEC-9398-6BA025A451F4> /usr/local/opt/utf8proc/lib/libutf8proc.2.dylib
       0x1081bb000 -        0x108241ff7 +libluajit-5.1.2.dylib (0) <4ABE53ED-73E8-385C-9BA6-712D50F85A16> /usr/local/opt/luajit/lib/libluajit-5.1.2.dylib
       0x10e05e000 -        0x10e0eecb7  dyld (733.8) <EBC07CB6-870A-3A8E-B48A-67F62EA161F3> /usr/lib/dyld
    0x7fff352e8000 -     0x7fff35768fe7  com.apple.CoreFoundation (6.9 - 1674.114) <5810CC45-FB5D-3A78-861F-7BE03F9B2FDD> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff69373000 -     0x7fff69375ff7  libDiagnosticMessagesClient.dylib (112) <45E85899-039F-3B99-8789-F497DD9916C2> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff6983b000 -     0x7fff6983cff3  libSystem.B.dylib (1281) <A2C26908-8802-3CA7-8B74-ED4A74AA152C> /usr/lib/libSystem.B.dylib
    0x7fff69b21000 -     0x7fff69b74ff7  libc++.1.dylib (800.7) <1D0CB627-8A78-329F-A679-1B5248FF4C59> /usr/lib/libc++.1.dylib
    0x7fff69b75000 -     0x7fff69b89fff  libc++abi.dylib (800.7) <7AF668FB-901D-3F45-BA0D-710A235A8D1F> /usr/lib/libc++abi.dylib
    0x7fff69b8a000 -     0x7fff69b8affb  libcharset.1.dylib (59) <56F66234-104F-3494-B336-598800CF3F71> /usr/lib/libcharset.1.dylib
    0x7fff6a5ed000 -     0x7fff6a5effff  libfakelink.dylib (149) <7296A5B3-EE44-34E6-810A-2A12C2D3EF68> /usr/lib/libfakelink.dylib
    0x7fff6a60e000 -     0x7fff6a6feff7  libiconv.2.dylib (59) <30414773-5E42-3976-B7C3-9BB8883792EE> /usr/lib/libiconv.2.dylib
    0x7fff6a6ff000 -     0x7fff6a957ff7  libicucore.A.dylib (64252.0.1) <0F9294A7-6EC0-3279-BF92-3233C89DFA0A> /usr/lib/libicucore.A.dylib
    0x7fff6b690000 -     0x7fff6b6c1fc6  libobjc.A.dylib (781.2) <7B72F50A-5381-36D7-A616-65D3EA9748A5> /usr/lib/libobjc.A.dylib
    0x7fff6bc46000 -     0x7fff6bc49ffb  libutil.dylib (57) <6CB26E6D-AD27-3FA8-8A30-4AFC3A2AE3F9> /usr/lib/libutil.dylib
    0x7fff6bd6c000 -     0x7fff6bd7effb  libz.1.dylib (76) <52250917-039C-3B46-8011-497FEACF3550> /usr/lib/libz.1.dylib
    0x7fff6c7e2000 -     0x7fff6c7e7ff3  libcache.dylib (83) <11C19883-6F99-390D-AF2A-A85A99DDFC48> /usr/lib/system/libcache.dylib
    0x7fff6c7e8000 -     0x7fff6c7f3fff  libcommonCrypto.dylib (60165) <FEE99884-61F0-3332-852B-B0BB8EFF2288> /usr/lib/system/libcommonCrypto.dylib
    0x7fff6c7f4000 -     0x7fff6c7fbfff  libcompiler_rt.dylib (101.2) <D7367E6D-A27D-3209-A3DB-A6F44582E502> /usr/lib/system/libcompiler_rt.dylib
    0x7fff6c7fc000 -     0x7fff6c805fff  libcopyfile.dylib (166.40.1) <91670D15-CB30-3277-8AA9-9A299CEAAE27> /usr/lib/system/libcopyfile.dylib
    0x7fff6c806000 -     0x7fff6c89dfdb  libcorecrypto.dylib (866.80.2) <3B110D82-B403-31E8-8109-8BBC79C928CE> /usr/lib/system/libcorecrypto.dylib
    0x7fff6c9b4000 -     0x7fff6c9f5ff0  libdispatch.dylib (1173.60.1) <5EF42E98-AD0D-3FAE-ABD4-46D791B8343F> /usr/lib/system/libdispatch.dylib
    0x7fff6c9f6000 -     0x7fff6ca2bff7  libdyld.dylib (733.8) <8B0DFE8A-42CF-32C8-B121-83C22BF25F69> /usr/lib/system/libdyld.dylib
    0x7fff6ca2c000 -     0x7fff6ca2cffb  libkeymgr.dylib (30) <7DADC026-70A8-390F-95AF-F3F345760F24> /usr/lib/system/libkeymgr.dylib
    0x7fff6ca3a000 -     0x7fff6ca3aff7  liblaunch.dylib (1738.80.8) <C4EA8803-E506-3514-9839-9BBECC819953> /usr/lib/system/liblaunch.dylib
    0x7fff6ca3b000 -     0x7fff6ca40ff7  libmacho.dylib (949.0.1) <395ABE7C-D2B1-343D-A451-9CEA98FDC12E> /usr/lib/system/libmacho.dylib
    0x7fff6ca41000 -     0x7fff6ca43ff7  libquarantine.dylib (110.40.3) <560961FC-1FEF-3F07-8406-17A36558870E> /usr/lib/system/libquarantine.dylib
    0x7fff6ca44000 -     0x7fff6ca45ff7  libremovefile.dylib (48) <E99833DE-CB1D-31AB-A948-2739AF503599> /usr/lib/system/libremovefile.dylib
    0x7fff6ca46000 -     0x7fff6ca5dfff  libsystem_asl.dylib (377.60.2) <21A259BC-F892-34EB-9A67-11232AD8913A> /usr/lib/system/libsystem_asl.dylib
    0x7fff6ca5e000 -     0x7fff6ca5efff  libsystem_blocks.dylib (74) <8B23F806-8153-3163-B5D8-2C3327E211D8> /usr/lib/system/libsystem_blocks.dylib
    0x7fff6ca5f000 -     0x7fff6cae6ff7  libsystem_c.dylib (1353.60.8) <99202CC3-2E27-3680-A8FF-5C516C485E90> /usr/lib/system/libsystem_c.dylib
    0x7fff6cae7000 -     0x7fff6caeaffb  libsystem_configuration.dylib (1061.80.3) <8A149700-51AA-3205-A9D4-FF2A7BFC5412> /usr/lib/system/libsystem_configuration.dylib
    0x7fff6caeb000 -     0x7fff6caeeff7  libsystem_coreservices.dylib (114) <CCC076FA-310D-3FC9-950D-41E0F8DDA5D2> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff6caef000 -     0x7fff6caf7fff  libsystem_darwin.dylib (1353.60.8) <31ACD3CC-6DD9-3F2E-B163-9342BE1D0AB0> /usr/lib/system/libsystem_darwin.dylib
    0x7fff6caf8000 -     0x7fff6caffffb  libsystem_dnssd.dylib (1096.60.2) <BEBB815A-065A-365E-9701-8E05A8CF2040> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff6cb00000 -     0x7fff6cb01ffb  libsystem_featureflags.dylib (17) <340AD606-7C39-3E6A-BAC3-EA1273FC27A4> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff6cb02000 -     0x7fff6cb4ffff  libsystem_info.dylib (538) <B0EBAE05-01AD-3D8E-92CC-5704394FF94A> /usr/lib/system/libsystem_info.dylib
    0x7fff6cb50000 -     0x7fff6cb7cff7  libsystem_kernel.dylib (6153.81.5) <23909F45-79C3-34C9-A28F-337915925E5E> /usr/lib/system/libsystem_kernel.dylib
    0x7fff6cb7d000 -     0x7fff6cbc4fcf  libsystem_m.dylib (3178) <7D775039-51B8-356E-82D7-98449065518A> /usr/lib/system/libsystem_m.dylib
    0x7fff6cbc5000 -     0x7fff6cbecfff  libsystem_malloc.dylib (283.60.1) <00190446-C6A8-3EA6-92D1-850EA85C84CE> /usr/lib/system/libsystem_malloc.dylib
    0x7fff6cbed000 -     0x7fff6cbfaffb  libsystem_networkextension.dylib (1095.60.2) <1E7A59D0-BBCD-3CB0-8AD1-D442A1A5268E> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff6cbfb000 -     0x7fff6cc04ff3  libsystem_notify.dylib (241) <AB3FAC47-A830-3158-8D99-DBC728CED1D6> /usr/lib/system/libsystem_notify.dylib
    0x7fff6cc05000 -     0x7fff6cc0efef  libsystem_platform.dylib (220) <3DAFCC01-B768-3FFC-AC59-47AAE86BBEA1> /usr/lib/system/libsystem_platform.dylib
    0x7fff6cc0f000 -     0x7fff6cc19fff  libsystem_pthread.dylib (416.60.2) <AAF506F4-9455-3CC4-8E0B-6791E3C0993C> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6cc1a000 -     0x7fff6cc1efff  libsystem_sandbox.dylib (1217.80.1) <C8F3841A-9364-3414-9E3F-9DE3D5FECF0C> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff6cc1f000 -     0x7fff6cc21fff  libsystem_secinit.dylib (62.80.1) <32F36517-9A1C-3D30-85C8-611A2F5E2355> /usr/lib/system/libsystem_secinit.dylib
    0x7fff6cc22000 -     0x7fff6cc29ffb  libsystem_symptoms.dylib (1238.60.1) <2EDF9CE8-4091-30A8-B125-0F25E579694A> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6cc2a000 -     0x7fff6cc40ff2  libsystem_trace.dylib (1147.80.3) <AE11B1AC-352A-37F0-BCA9-055609070104> /usr/lib/system/libsystem_trace.dylib
    0x7fff6cc42000 -     0x7fff6cc47ffb  libunwind.dylib (35.4) <E867ACDE-EADE-3C91-A2A4-0C401788FD47> /usr/lib/system/libunwind.dylib
    0x7fff6cc48000 -     0x7fff6cc7dffe  libxpc.dylib (1738.80.8) <51E3E807-9133-3605-BB5F-D59ED6404ABF> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 2
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 51132
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=370.4M resident=0K(0%) swapped_out_or_unallocated=370.4M(100%)
Writable regions: Total=77.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=77.1M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Dispatch continuations            8192K        1 
Kernel Alloc Once                    8K        1 
MALLOC                            51.6M       84 
MALLOC guard page                   16K        4 
MALLOC_LARGE (reserved)            160K        2         reserved VM address space (unallocated)
STACK GUARD                       56.0M        3 
Stack                             16.5M        3 
VM_ALLOCATE                        256K        2 
__DATA                            2214K       58 
__DATA_CONST                       232K        9 
__LINKEDIT                       354.3M       11 
__OBJC_RO                         32.0M        1 
__OBJC_RW                         1780K        2 
__TEXT                            16.1M       56 
__UNICODE                          564K        1 
mapped file                         28K        1 
shared memory                       48K        6 
===========                     =======  ======= 
TOTAL                            540.0M      246 
TOTAL, minus reserved VM space   539.8M      246 
```

**Comment by dm1try** [comment]
reproducible on-liner:
```
nvim -u NORC --cmd 'set nowrap|autocmd TermOpen * startinsert' -c 'call feedkeys("4000ai\<esc>:terminal!\<cr>")' 
```

I found the cause of bad access,
virtual columns count is greater than a reserved buffer size for term_attributes when `nowrap` is set:
https://github.com/neovim/neovim/blob/29b1a4761a9fadfa9de05cfd9c8aad281fc29791/src/nvim/screen.c#L2606-L2609
https://github.com/neovim/neovim/blob/29b1a4761a9fadfa9de05cfd9c8aad281fc29791/src/nvim/screen.c#L2787-L2790
so this code for highlighting fails
https://github.com/neovim/neovim/blob/29b1a4761a9fadfa9de05cfd9c8aad281fc29791/src/nvim/screen.c#L4134

I'm not sure how to fix it right

@lourenci as a workaround, you can try set `wrap` before `startinsert`
`autocmd TermOpen set wrap|term://* startinsert`

**Comment by lourenci** [comment]
Thank you for your feedback, @dm1try.

Since my main problem is with `fzf.vim` that starts a terminal to fuzzy, I'll wait for the official solution being merged.

**Comment by erw7** [comment]
@dm1try Thank you for debugging! When I thought about it, the `term_attrs` are all initialized to zero. Therefore, the part of `linebuf_attr` that exceeds the width of the terminal will be zero. Also, the part that exceeds the term_attrs should be fine by assigning zero (no attribute). I fixed it with that idea.

**Comment by tomdalling** [comment]
> as a workaround, you can try set `wrap` before `startinsert`
> `autocmd TermOpen set wrap|term://* startinsert`

I believe the workaround is supposed to be:

```vim
autocmd TermOpen * set wrap|startinsert
```

This is my config, which starts insert mode on `BufEnter` instead of `TermOpen`:

```vim
augroup MyTerminal
  autocmd!
  " workaround for a segfault: https://github.com/neovim/neovim/issues/11548#issuecomment-583081783
  au TermOpen * setlocal wrap
  " immediately enter insert mode when switching to a terminal
  au BufEnter term://* startinsert!
augroup END
```

**Comment by john-kurkowski** [comment]
Still getting this crash. Seemingly since I switched to Neovim 1-2 months ago. It happens during fzf.vim popup enter key to select an item, or escape key to exit the popup without selecting anything. Similar setup to OP. NVIM v0.6.0-dev+1536-g6f48c018b. Similar stacktrace. 

[nvim_2021-07-23-112329.crash.txt](https://github.com/neovim/neovim/files/6870656/nvim_2021-07-23-112329.crash.txt)
