### ISSUE TITLE
win/MSVC: multibyte chars displayed incorrectly

### ISSUE THREAD

**Issue by matteocoder** [neovim/neovim#11749]
- `nvim --version`: 0.4.3 installed via Chocolatey
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Windows 10 1909 64-bit
- Terminal name/version: Powershell 5, Cmder 1.3.14
- `$TERM`: cygwin (for Cmder)

### Steps to reproduce using `nvim -u NORC`
1. Type some characters in insert mode;
2. return to normal mode and press `u` until you are at the first change.

### Actual behaviour
Neovim displays accented characters like this:
`Questa <e8> gi<e0> la prima modifica`
![nvimpsaccent](https://user-images.githubusercontent.com/22897138/73031064-619ea180-3e3b-11ea-8f55-87cd0ab97f02.PNG)

### Expected behaviour
Neovim should display the accented characters correctly:
`Questa è già la prima modifica`

This issue also happens with Neovim-qt. I've tried to use the Windows setting that lets you use an UTF-8 encoding for all applications, but so far I had no luck.

Thank you for your attention and thanks for developing this awesome editor.

**Comment by erw7** [comment]
This problem probably occurs when compiling with `MSVC`. It works fine with `nvim` I compiled with `MinGW`.

![nvim](https://user-images.githubusercontent.com/11682285/73049019-66586980-3ebe-11ea-9f9a-cd284981b269.jpg)

**Comment by matteocoder** [comment]
Thank you for your quick reply @erw7 .
In this case what should I do? Should I contact the chocolatey package maintainers?

**Comment by justinmk** [comment]
> Should I contact the chocolatey package maintainers?

No, they're using the builds we provide which are built with MSVC. 

> This problem probably occurs when compiling with `MSVC`

@erw7  Why? I thought libintl/iconv stuff was fixed?

**Comment by justinmk** [comment]
@matteocoder can you please try the zip here : https://github.com/neovim/neovim/releases/tag/nightly

**Comment by erw7** [comment]
This seems to be a libintl/libiconv problem. `gettext` compiled with `MSVC` seems to return a string that is not utf-8 encoded (è->0xe8, à->0xe0).

**Comment by justinmk** [comment]
> `gettext` compiled with `MSVC` seems to return a string that is not utf-8 encoded (è->0xe8, à->0xe0).

Maybe we just need to change the flags we build it with.

**Comment by matteocoder** [comment]
@justinmk I've tried the pre-release build you gave me, but unfortunately the problem is still there.

**Comment by erw7** [comment]
After all, the problem was that `HAVE_ICONV` was not defined when building `gettext`. I created #11774.

**Comment by justinmk** [comment]
@matteocoder fix is on master branch. Please try nightly build in 24 hours, after CI has time to post a new build: https://github.com/neovim/neovim/releases/tag/nightly

**Comment by matteocoder** [comment]
@justinmk I can confirm that the problem is solved in the latest nightly. Thank you guys.
