### ISSUE TITLE
Make `cwd` an option

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#15936]
### Feature already in Vim?

No

### Feature description

To avoid an X Y problem, here's my usecase:

I want to set the current working directory on a buffer basis, programmatically, and without having to change the focus from the current tabpage/window/buffer.

I think the best way to enable this usecase is to make `cwd` an option. It would have the following advantages:
- No need to create custom apis (e.g. `nvim_buf_get_cwd()`/`nvim_buf_set_cwd()`)
- (I think) Allows re-using the existing option-shadowing code
- Makes `cwd` stop being "special" (currently can only be set with `cd`, `tcd` or `lcd`, requires using `getcwd()` for reading...).

Let me know if this sounds reasonable, I'll try to draft a PR if it is.

**Comment by zeertzjq** [comment]
> > Permission may be another problem. Should a non-active window's working directory be allowed to be changed to a directory the current user doesn't have access to?
> 
> Don't see how that happens, the shell and OS would deny the change of directory if the user has no permissions, nvim should just handle the error
> 
> I'm thinking about Linux, I imagine is similar on windows?

But setting the working directory of a non-active window doesn't require actually changing the directory.

**Comment by zeertzjq** [comment]
> Good point 👍
> 
> An improvement for the `{t,l}cd` family of commands would be to not lose the previous directory (for `{t,l}cd -`) when the command fails.
> 
> Currently before the `cd` command runs it stores the current working directory as the previous one, anticipating a successful change. If the change fails the it keeps the current, but the previous directory was already changed therefore the reference is lost, and `cd -` doesn't take you back since is equivalent to changing to the current working directory.

Probably need to wait for <https://github.com/vim/vim/issues/8983>.

**Comment by zeertzjq** [comment]
Maybe this can just be worked around with `win_execute()` or `nvim_win_call()`? For example:
```lua
vim.api.nvim_win_call(win_id, function()
  vim.cmd('noautocmd lcd .')  -- ensure the window has a local directory
  vim.fn.chdir(dir)  -- chdir() function doesn't require escaping
end)
```

There is currently a bug that the working directory won't change back after this though. Vim's `win_execute()` also has that bug, so I think that should be fixed in Vim first.

**Comment by glacambre** [comment]
@zeertzjq The `autocd` setting does this already. It doesn't suit my usecase because I want to set the `cwd` for buffers that do not have an underlying file.

**Comment by zeertzjq** [comment]
Does this have anything to do with `autocd`? That `lcd .` is only used so `chdir()` (which doesn't require escaping) changes the local directory of that window. If you already know that the directory doesn't require escaping then `win_execute(win_id, 'lcd ' .. dir)` is enough.

**Comment by glacambre** [comment]
>Does this have anything to do with autocd?

I thought it did, but since you're asking this question I must have misunderstood you :).

>win_execute(win_id, 'lcd ' .. dir) is enough.

This doesn't solve for the issue of changing the current buffer in a window though, so you have to setup WinEnter and BufWinEnter autocmds to call this code every time. And then you have to add code to clear these autocmds to be able to revert back to the window/tab/global's `cwd`.

That becomes a lot of effort for something that could be as simple as `:setlocal cwd=...` IMO.

**Comment by zeertzjq** [comment]
Oh, I didn't notice the "on a buffer basis" in the top comment.

**Comment by zeertzjq** [comment]
My thoughts on this:
- The option can be named like `'bufdir'`
- Its behavior is like `'autochdir'` but with a custom directory
- `'autochdir'` is ignored if `'bufdir'` is set
- For `DirChanged` maybe we need to add a new patter
- There is no option that is both buffer-local and window-local, so `:lcd` needs to be retained

**Comment by zeertzjq** [comment]
Wait, can't this just be implemented using `BufEnter` autocommands?

**Comment by glacambre** [comment]
>can't this just be implemented using BufEnter autocommands

Yes and no. Unfortunately you also need a WinEnter autocommand (because when you move from a window to another that displays the same buffer the BufEnter autocmd won't be triggered). You need the logic to remember that the `cwd` of a non-current window might not be correct, the logic to back up the window's CWD, the logic to clear the autocommands to be able to go back to window/tab/global cwd. That's a lot of effort for something that should really be as simple as `:setlocal cwd=...`.

**Comment by zeertzjq** [comment]
Oh, I forgot `:cd` clears local working directory.

**Comment by glacambre** [comment]
I tried to implement this and found it pretty hard. Since the only reason I wanted `cwd` as an option was to implement #16740 as a plugin, and that I now have implemented #16740, I don't need `cwd` as an option anymore, so I'll close this issue.

Feel free to re-open if you still want/need it :).
