### ISSUE TITLE
[bug] Background color redraw issue with term module removal and termkey/unibilium changes

### ISSUE THREAD

**Issue by Happy-Dude** [neovim/neovim#2005]
I am confirming the issue reported by @bigeagle at his last comment in #1820 (and referencing #1997 because of @tarruda's continued work):

> Hi, using the merged version, there're still a problem that the terminal's background color cannot be automatically "resetted". To repeat this bug, nvim -u NONE and try to show some error message, e.g. :q on an unsaved file and there would be an error message with red bg color, now press : and the red background is still there.
> I'm using xterm-256color.
> ![687474703a2f2f692e696d6775722e636f6d2f3358514a44735a2e706e67](https://cloud.githubusercontent.com/assets/1098725/6235791/032bd51a-b6b3-11e4-9911-9c8cdefca852.png)

I am noticing this bug also affects redrawing past the color column
```viml
if exists('+colorcolumn')
    set colorcolumn=81
else
    ...
```

And I see the following in my terminal:
![screen shot 2015-02-17 at 2 45 10 pm](https://cloud.githubusercontent.com/assets/1098725/6235856/9e6b20ee-b6b3-11e4-8121-79a74f74c6de.png)

The following are details of my Neovim version and platform:

    NVIM 0.0.0-alpha+201502170110 (compiled Feb 17 2015 01:51:39)
    Commit: 66a03a7385dfd11503d22d8cc9dc6a972e27dcc2
    Build type: RelWithDebInfo
    Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-ijeEOa/build/config -I/tmp/neovim-ijeEOa/src -I/tmp/neovim-ijeEOa/.deps/usr/include -I/tmp/neovim-ijeEOa/.deps/usr/include -I/tmp/neovim-ijeEOa/.deps/usr/include/luajit-2.0 -I/tmp/neovim-ijeEOa/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-ijeEOa/build/src/nvim/auto -I/tmp/neovim-ijeEOa/build/include

    Installed With: Homebrew (using neovim/homebrew-neovim tap from the neovim repository)
    Platform: OS X 10.9.5
    uname -a: Darwin 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64
    Shell: zsh running in iTerm2

@bigeagle seems to be running into this error with a build of nvim on a Linux variant.

**Comment by Happy-Dude** [comment]
This seems to happen with the default color scheme for some add reason. I am not noticing redraw issues when I use my color scheme settings. (Nor do I notice the issue in vim with the default color scheme either.)

**Comment by tarruda** [comment]
Should be fixed in #2007

**Comment by fmoralesc** [comment]
@tarruda I can confirm. :+1:

**Comment by tarruda** [comment]
#2007 was merged

**Comment by oakes** [comment]
I am still getting redraw issues with the latest merge. It solved it to a certain extent, because I no longer see anything right away. However, when I scroll down and then scroll back up, my screen is filled as shown in the image. The issue does not occur when I turn my colorcolumn off.

![redraw](https://cloud.githubusercontent.com/assets/216147/6259094/ea90528e-b79c-11e4-9081-8b476aedbcbe.png)

**Comment by tarruda** [comment]
@oakes whats your terminal emulator/TERM variable?

**Comment by oakes** [comment]
The screenshot was taken in an app I am developing, which uses the VteTerminal widget. However, I ran a standalone copy of nvim with the latest commit (866da6d) in the built-in OS X Terminal app and got similar results (I'm on 10.9.5 and my $TERM returns xterm-256color). This issue does not occur on Ubuntu 14.04.

![redraw2](https://cloud.githubusercontent.com/assets/216147/6267582/3732306e-b813-11e4-8e00-0a4dddfdceb9.png)

**Comment by oakes** [comment]
It seems that the colorcolumn doesn't show up at all on Ubuntu 14.04 in the built-in Terminal app.

**Comment by tarruda** [comment]
@oakes I haven't been able to reproduce this, can you post a vimrc that causes the issue with OSX default terminal app?

**Comment by oakes** [comment]
```
set colorcolumn=101
set tabstop=4
set shiftwidth=4
set expandtab
set hidden
set mouse=a
set number
set noswapfile
syntax on
```

To be sure I wasn't doing anything wrong, I just installed it via homebrew-neovim. Running `nvim --version` shows that it is based on 0a7cd65cbce8eb7fc488fb1b37fe46783e9d6e56. I still see the issue by scrolling by using Ctrl+U/D or Ctrl+F/B.

**Comment by tarruda** [comment]
@oakes does #2025 fixes the problem for you?

**Comment by oakes** [comment]
It does indeed. Thanks!
