### ISSUE TITLE
Pressing HOME and END keys don't move the cursor in insert mode.

### ISSUE THREAD

**Issue by khalidchawtany** [neovim/neovim#2028]
Pressing **HOME** key or **END** key to move to the beginning or end of a line in insert mode does not move  the cursor.
I am using:
```
NVIM 0.0.0-alpha+201502200943 (compiled Feb 20 2015 15:53:21)
Commit: 9894720a0557cb80e11d33cb3b3a8fbf23827b9c
```

```
>> echo $TERM
screen-256color

>> infocmp $TERM  
#       Reconstructed via infocmp from file: /usr/share/terminfo/73/screen-256color
screen-256color|GNU Screen with 256 colors,
        am, km, mir, msgr, xenl,
        colors#256, cols#80, it#8, lines#24, ncv#3, pairs#32767,
        acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=^M,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
        cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
        dl1=\E[M, ed=\E[J, el=\E[K, el1=\E[1K, enacs=\E(B\E)0,
        flash=\Eg, home=\E[H, ht=^I, hts=\EH, ich=\E[%p1%d@,
        il=\E[%p1%dL, il1=\E[L, ind=^J, initc@, is2=\E)0, kbs=^H,
        kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, kend=\E[4~, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf2=\EOQ, kf3=\EOR, kf4=\EOS,
        kf5=\E[15~, kf6=\E[17~, kf7=\E[18~, kf8=\E[19~, kf9=\E[20~,
        khome=\E[1~, kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM, rmacs=^O,
        rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[23m,
        rmul=\E[24m, rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        sgr=\E[0%?%p6%t;1%;%?%p1%t;3%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;m%?%p9%t\016%e\017%;,
        sgr0=\E[m\017, smacs=^N, smcup=\E[?1049h, smir=\E[4h,
        smkx=\E[?1h\E=, smso=\E[3m, smul=\E[4m, tbc=\E[3g,
```

**Comment by tarruda** [comment]
@khalidchawtany do you experience this outside tmux? if so, whats the output of `infocmp $TERM` outside it?

**Comment by khalidchawtany** [comment]
@tarruda  this does not occur outside **tmux**

```
>> infocmp $TERM

#	Reconstructed via infocmp from file: /usr/share/terminfo/78/xterm-256color
xterm-256color|xterm with 256 colors,
	am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
	colors#256, cols#80, it#8, lines#24, pairs#32767,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
	dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K, el1=\E[1K,
	flash=\E[?5h$<100/>\E[?5l, home=\E[H, hpa=\E[%i%p1%dG,
	ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
	ind=^J, indn=\E[%p1%dS,
	initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
	invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
	kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
	kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^H,
	kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
	kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
	kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
	memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
	rin=\E[%p1%dT, rmacs=\E(B, rmam=\E[?7l, rmcup=\E[?1049l,
	rmir=\E[4l, rmkx=\E[?1l\E>, rmm=\E[?1034l, rmso=\E[27m,
	rmul=\E[24m, rs1=\Ec, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, smacs=\E(0, smam=\E[?7h, smcup=\E[?1049h,
	smir=\E[4h, smkx=\E[?1h\E=, smm=\E[?1034h, smso=\E[7m,
	smul=\E[4m, tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n,
	u8=\E[?1;2c, u9=\E[c, vpa=\E[%i%p1%dd,
```

**Comment by Pyrohh** [comment]
Does this also happen in vim? If so, I'm not sure it's an issue with nvim. I don't know what shell you're using, but I've had a similar issue when I used zsh, which didn't seem to able to recognize the HOME and END keys without this:
```
# Create a zkbd compatible hash.
# To add other keys to this hash, see 'man 5 terminfo'
typeset -A key

key[Home]=${terminfo[khome]}
key[End]=${terminfo[kend]}
key[Insert]=${terminfo[kich1]}
key[Delete]=${terminfo[kdch1]}
key[Up]=${terminfo[kcuu1]}
key[Down]=${terminfo[kcud1]}
key[Left]=${terminfo[kcub1]}
key[Right]=${terminfo[kcuf1]}

# Setup keys accordingly
[[ -n "${key[Home]}"     ]] && bindkey "${key[Home]}"		beginning-of-line
[[ -n "${key[End]}"      ]] && bindkey "${key[End]}"		end-of-line
[[ -n "${key[Insert]}"   ]] && bindkey "${key[Insert]}"		overwrite-mode
[[ -n "${key[Delete]}"   ]] && bindkey "${key[Delete]}"		delete-char
[[ -n "${key[Up]}"       ]] && bindkey "${key[Up]}"			up-history
[[ -n "${key[Down]}"     ]] && bindkey "${key[Down]}"		down-history
[[ -n "${key[Left]}"     ]] && bindkey "${key[Left]}"		backward-char
[[ -n "${key[Right]}"    ]] && bindkey "${key[Right]}"		forward-char

# Make sure the terminal is in application mode when zle is
# active. Only then are the values from $terminfo valid.
if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
	function zle-line-init () {
	printf '%s' "${terminfo[smkx]}"
}
```

**Comment by khalidchawtany** [comment]
@Pyrohh I use **zsh**  and in **vim** those keys work as expected. This issue happens only in **NeoVim**.

**Comment by Pyrohh** [comment]
Thank you for clarifying. Do your HOME/END keys work in all other terminal programs, i.e. those using readline such as `bc`?

**Comment by khalidchawtany** [comment]
Yep, I just tried it again, those keys work everywhere except **NeoVim**.

**Comment by tarruda** [comment]
@khalidchawtany does this happen with nvim -u NONE -N? If not, what are your ttimeout/ttimeoutlen settings? Also, what happens when you enter insert mode and type `<c-v><home>`?

**Comment by khalidchawtany** [comment]
@tarruda, yes it does happen with ```nvim -u NONE -N```. The result of ```<c-v><home>``` is just NOTHING!!!! When I press ```<c-v>``` this ```^``` is shown and then I press ```<home>``` and ```<end>``` key and the sign is still there, as if no key was pressed after If I press page up key ```<PageUp>``` is printed on the screen. This means that ```<home>``` and ```<end>``` keys are not processed at all.

**Comment by tarruda** [comment]
@khalidchawtany if you execute `xxd` without arguments and type `<home><end><c-d><c-d>` whats the output?

**Comment by khalidchawtany** [comment]
@tarruda here is the result:
 ```
>> xxd
^[[1~^[[4~0000000: 1b5b 317e 1b5b 347e                      .[1~.[4~
```

**Comment by tarruda** [comment]
@khalidchawtany this is exactly the same as mine. Maybe unibilium is failing to read your terminfo database? What happens if you apply  this patch?

```diff
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 0d366c2..5d30917 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -101,6 +101,7 @@ void tui_start(void)
   // setup unibilium
   data->ut = unibi_from_env();
   if (!data->ut) {
+    abort();
     // For some reason could not read terminfo file, use a dummy entry that
     // will be populated with common values by fix_terminfo below
     data->ut = unibi_dummy();
```

**Comment by khalidchawtany** [comment]
I did apply the patch and ```make install``` and then when I ran ```nvim``` from terminal I got .
```
[1]    29894 abort      ./nvim
```
Maybe I am doing something wrong. Since I always use **HomeBrew** to build *NeoVim**.

I will try to build again :)

**Comment by tarruda** [comment]
> Maybe I am doing something wrong. Since I always use HomeBrew to build NeoVim*.

You aren't doing anything wrong, thats exactly what I expected as the result of this patch.

That means unibilium is not finding your terminfo database, I will try to figure out whats wrong in my OSX vm and send a patch to unibilium later.

**Comment by khalidchawtany** [comment]
Thanks @tarruda.

**Comment by tarruda** [comment]
@khalidchawtany can you install from my custom [homebrew formula](https://github.com/neovim/homebrew-neovim/pull/29)? I'm not familiar with homebrew but I think this might work:

```
brew tap tarruda/homebrew-neovim
brew install --HEAD neovim
```

**Comment by khalidchawtany** [comment]
@Tarruda thanks for the quick fix, the keys work as expected now.

**Comment by tarruda** [comment]
@khalidchawtany credit goes to @mauke for quickly fixing the problem. I'm gonna update master with the new unibilium version

**Comment by tarruda** [comment]
Fixed by #2039

**Comment by rainerborene** [comment]
@tarruda just out of curiosity, but how did you install osx vm?

**Comment by tarruda** [comment]
@rainerborene I followed [this tutorial](http://www.macbreaker.com/2013/01/iatkos-ml2-mountain-lion-virtualbox.html). Be warned that OSX vms are very slow(Though it is possible to do some command-line development with tmux and ssh)

**Comment by yshui** [comment]
I'm facing the same issue on linux, with unibilium 1.1.2

**Comment by assaf758** [comment]
Hi, I have this exact issue (only on neovim + tmux), so maybe its not resolved completely.
My distribution is Junest (up-to-date arch over ubuntu)

**Comment by art-solopov** [comment]
I have the same issue with Ubuntu 14.04, NeoVim 0.1.2-dev, tmux 2.0.

**Comment by wsdjeg** [comment]
@art-solopov I am using ubuntu 16.40 gnome-terminal ,and I encount this issue also in ubuntu 14.04,when I update my os to 14.10 - 16.04 ,this issue is gone.It is the issue of the os ,not vim or neovim ,I think your Ctrl+home or Ctrl+end also can not works in vim .
install neovim from ppa source by apt-get manager
everthing works well for ,in insert mode. 
HOME goto the begin of current line
END goto the end of current line
Ctrl+Home goto the begin of current file
Ctrl+End goto the end of current file ,

**Comment by marcosnils** [comment]
@tarruda same thing going on in ubuntu 15.04 + tmux 1.9.

```NVIM 0.1.2-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-XFC677/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu15.04.1/build/config -I/build/neovim-XFC677/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu15.04.1/src -I/build/neovim-XFC677/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu15.04.1/.deps/usr/include -I/build/neovim-XFC677/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu15.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-XFC677/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu15.04.1/.deps/usr/include -I/build/neovim-XFC677/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu15.04.1/.deps/usr/include -I/build/neovim-XFC677/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu15.04.1/.deps/usr/include -I/build/neovim-XFC677/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-XFC677/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu15.04.1/build/src/nvim/auto -I/build/neovim-XFC677/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu15.04.1/build/include
Compiled by buildd@lgw01-40

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by leon-barrett** [comment]
For the recent linux issue commented by some folks, it looks like it's a `TERM` issue. The wiki now has [a note on it.](https://github.com/neovim/neovim/wiki/Troubleshooting#home-or-some-other-special-key-doesnt-work)

**Comment by jcfaria** [comment]
I wonder this bug is related to 256 color scheme, tmux and nvim.
My .bashrc is like below:

```
alias ls="ls --color=auto"
alias grep="grep --colour=auto"
alias egrep="egrep --colour=auto"

# enable bash completion in interactive shells
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# http://vim.wikia.com/wiki/256_colors_in_vim
if [ -e /usr/share/terminfo/x/xterm+256color ]; then
  export TERM='xterm-256color'
else
  export TERM='xterm-color'
fi

# If not running interactively, do not do anything
[[ $- != *i* ]] && return
[[ -z "$TMUX" ]] && exec tmux
```
I use both: vim and nvim. 

All files in ~/.config/nvim are simbolic links to related vim:
- ~/.config/nvim/autoload -> link to ~/.vim/autolad
- ~/.config/nvim/plugged -> link to ~/.vim/plugged
- ~/.config/nvim/init.vim -> link to ~/.vimrc

because I use vim-plug as plugin manager.
With this .bashrc vim works fine, nvim not.

If the the part of 256 color scheme is commented the keys HOME and AND works for both.

```
## enable bash completion in interactive shells
#if ! shopt -oq posix; then
#  if [ -f /usr/share/bash-completion/bash_completion ]; then
#    . /usr/share/bash-completion/bash_completion
#  elif [ -f /etc/bash_completion ]; then
#    . /etc/bash_completion
#  fi
#fi
```

**Comment by leon-barrett** [comment]
@jcfaria Yes--inside tmux, `TERM=xterm-256color` seems to be bad. Instead, you should set `TERM=screen-256color`.

Also, that is now [described in the wiki](https://github.com/neovim/neovim/wiki/FAQ#home-or-some-other-special-key-doesnt-work). @jcfaria, given that you didn't easily find that, is there a better way to make that easily findable? Where would you have searched for that?

**Comment by ZyX-I** [comment]
@jcfaria Never use vim.wikia, it mostly contains incomplete and/or incorrect advices. Specifically in your case:

1. For tmux one must not use xterm-256color, there is screen-256color as @leon-barrett mentioned. Other terminal emulators may also have other values, AFAIR st (simple terminal) has its own $TERM. Though wikia explicitly says here “to enable colors *on XTerm*”.
2. Dunno about pdksh, but zsh is not sourcing ~/.profile (unless it is invoked in “compatibility mode”: e.g. using a symlink `sh -> zsh`). Also used terminal emulator is not guaranteed to run a *login* shell, so ~/.profile may be not sourced at all.
3. Actually you must not edit $TERM in ~/.profile at all in any case: this is not going to work correctly under a number of conditions, including using `<C-A-F1>` “kernel” terminals (where $TERM is linux and should stay as-is). Modern terminal emulators either already export correct $TERM or allow configuring themselves to export right value.
4. You should not `set t_Co` to anything, if Vim is not able to detect correct number of colors based on $TERM environment variable and relevant termcap/terminfo entry then it indicates that something is wrong and needs to be fixex elsewhere.

**Comment by jcfaria** [comment]
Dears @leon-barrett and @ZyX-I, many thanks for all. It is working fine here now.

**Comment by juur** [comment]
I found that with a TERM setting of "xterm", "xterm-color" or "xterm-256color", nvim (0.1.5) didn't handle HOME and END; without tmux/screen, under Linux, via putty. Even with "-u NONE -N". However, all were working with vim (7.4), including vim with "-u NONE -N". I then tried screen-256color (without screen) and HOME and END seemed to start working again in insert mode.
There is clearly something different in neovim vs. vim.
