### ISSUE TITLE
Update windows build instructions

### ISSUE THREAD

**Issue by luukvbaal** [neovim/neovim#22752]
### Problem

Building mpack dependency requires md5sum, openssl or md5:

    Error: Failed producing checksum: no MD5 checker tool available, please install md5sum, openssl or md5 in your system

### Steps to reproduce

Build with MSVC Powershell:
```
cmake -S cmake.deps -B .deps -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build .deps
```

### Expected behavior

Avoid dependency or update build instructions @dundargoc

Fix typo https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msvc-powershell step 3:
```diff
- cmake -B build -G Ninja CMAKE_BUILD_TYPE=RelWithDebInfo
+ cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo
```

### Neovim version (nvim -v)

NVIM v0.9.0-dev-701+g34b973b1d9

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 11

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

**Comment by justinmk** [comment]
Fixed typo, thanks! https://github.com/neovim/neovim/wiki/Building-Neovim/_compare/8c260fadbefd3461108d1c2636741bf4a141f01e

**Comment by dundargoc** [comment]
Wait, no. The real problem is that mpack has a md5 dependency that suddenly appeared. This is a weird check on windows, so need to add this deps to wiki or more preferably find a way to remove it.

**Comment by erw7** [comment]
Related? https://github.com/luarocks/luarocks/issues/1443, https://github.com/luarocks/luarocks/issues/1001

**Comment by luukvbaal** [comment]
> Related? https://github.com/luarocks/luarocks/issues/1443, https://github.com/luarocks/luarocks/issues/1001

Not sure, for me the issue was just the fact that an MD5 checker is required was missing from the build instructions. Once I installed `opensll` the build worked fine. Those issues seem to mention a failure in detecting said md5 checker.

**Comment by erw7** [comment]
`luarocks` installs tools including `md5sum.exe`. Thus, there should normally be no problem without installing additional tools. If `io.open` of `variables = { MD5SUM = "..." }` fails, the tool is retrieved from the `PATH`. Therefore, if `md5sum.exe`, etc. is in the `PATH`, this problem is not apparent. Nevertheless, the problem of `luarocks` still exists. Therefore we should solve `luarocks` problem instead of adding such information to the document. 

https://github.com/luarocks/luarocks/blob/9a3c5a879849f4f411a96cf1bdc0c4c7e26ade42/src/luarocks/fs/lua.lua#L117-L150

Or downgrade the `luarocks` version to a less problematic version until the problem is resolved, as it is probably directly caused by 46079c3.

**Comment by xtance** [comment]
Downgrading to 3.8.0 removes this error thanks to @erw7

**Comment by clason** [comment]
Note that we get similar but transient failures on CI as well; I haven't been able to reproduce them consistently, and restarting the workflow has usually let them pass.

**Comment by dundargoc** [comment]
Somewhat of a tangent, but maybe we should add a docker build of the big 3 platforms for build system changes only? It's basically impossible to catch these scenarios on regular CI as basically everything is included in the github runners.

**Comment by erw7** [comment]
> Note that we get similar but transient failures on CI as well; I haven't been able to reproduce them consistently, and restarting the workflow has usually let them pass.

I don't see how this issue could cause inconsistent errors. If the cause of the error is this issue, then `PATH` environment variable of CI is not consistent. Such a thing is inconceivable.

**Comment by dundargoc** [comment]
> Related? https://github.com/luarocks/luarocks/issues/1443, https://github.com/luarocks/luarocks/issues/1001

@erw7 nice find.

I think we'll need to revert the luarocks bump, installing on windows is already difficult without this.

**Comment by dundargoc** [comment]
Solved by https://github.com/neovim/neovim/pull/22872
