### ISSUE TITLE
100% Cpu usage and hang on quit for Rust. Affects version 0.10 but not version 0.9

### ISSUE THREAD

**Issue by surfdude75** [neovim/neovim#23725]
### Problem

Nvim takes 100% of CPU all time but works as expected and hangs when quitting.

Tested in 2 different Nvim Rust setups. One using LazyNvim and another with just required plugins.

The problem happens only in version 0.10 and not in version 0.9.

### Steps to reproduce

Tested using the 2 follow setups for Rust

Setup 1 - LazyVim + Rust setup bellow
https://gist.github.com/surfdude75/35e5bff1fdd517ec570cab36251ea850

Setup 2 - More Basic setup
https://rsdlt.github.io/posts/rust-nvim-ide-guide-walkthrough-development-debug/

NeoVim 0.10.0 installed thru https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable works but Nvim takes a 100% and hang on quit for both setups.

It works for both setups using NeoVim 0.9.0 installed thru snap on Ubuntu.

### Expected behavior

Do not take 100% of CPU and quit to console after :q!

### Neovim version (nvim -v)

NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

not tested

### Operating system/version

Ubuntu 22.04.2 LTS

### Terminal name/version

GNOME Shell 42.5

### $TERM environment variable

xterm-256color

### Installation

snap

**Comment by glepnir** [comment]
could you try the min config https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua  to test ? I can't reproduce it, recently i write some rust_analyzer codes. it works fine for me .

![image](https://github.com/neovim/neovim/assets/41671631/ee596b4f-4150-4b21-9ab2-bafd813819df)

**Comment by Shougo** [comment]
> NeoVim 0.10.0 installed thru https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable works but Nvim takes a 100% and hang on quit for both setups.

I think it is not the latest version.
Please upload more detailed neovim version number by `nvim --version`.

**Comment by Shougo** [comment]
I think the problem is https://github.com/neovim/neovim/issues/23595.

**Comment by folke** [comment]
This is probably caused by the new watch files implementation. Very recently though, it has been disabled by default. It actually was already disabled by default, but some lsps still added watches through dynamic registration even when dynamic registration for watch files was not enabled. This was fixed somewhere last week, so best to try a nightly built.

**Comment by tkinz27** [comment]
@Shougo the neovim nightly debian has been failing to build for almost 2 weeks now. From the build logs it looks like networking issues, but I do not know who to get into contact with to try to get it fixed up

**Comment by Palpatineli** [comment]
Sorry for this likely naïve question: my understanding is the official patch has been applied with https://github.com/neovim/neovim/commit/79a5b89d66db74560e751561542064674e980146 but when I use the nightly build NVIM v0.10.0-dev-539+g72a6643b1 I'm still having this issue (but for python files configured with pyright instead), and the above fix still works. Is the patch not getting into the nightly build, or am I missing something here?

**Comment by folke** [comment]
I believe the new implementation should be more efficient and it also excludes a number of known globs:

```lua
parse('**/.git/{objects,subtree-cache}/**')
  + parse('**/node_modules/*/**')
  + parse('**/.hg/store/**')
```

I don't see anything there for python projects though.

For me personally, I don't think lsp support for watch files brings a lot of value (at least not for the LSP servers I'm using), so I just keep it disabled in my config for now.

**Comment by meridionaljet** [comment]
Just a note to confirm that in `NVIM v0.10.0-dev-601+gd55d7646c`, I get frequent CPU spikes associated with huge volumes of I/O requests and `futex` locks in `strace` output when the editor is idling, particularly noticeable when opening a Python file in a Python environment that contains large libraries like `numpy`.

The config fragment offered by @folke does work.

**Comment by justinmk** [comment]
Duplicate of https://github.com/neovim/neovim/issues/23291
