### ISSUE TITLE
Commit #0081549 broke multiple plugins

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#24897]
### Problem

Commit [#0081549](https://github.com/neovim/neovim/commit/008154954791001efcc46c28146e21403f3a698b) has broken multiple plugins, including:
+ [Telescope](https://github.com/nvim-telescope/telescope.nvim): Won't display items in when amount of items<window height
+ [nvim-cmp](https://github.com/hrsh7th/nvim-cmp): Can't use select_next_item multiple times in cmdline

### Steps to reproduce

Example of Telescope not working:
Use the minimal config:
```lua
for name, url in pairs{
  'https://github.com/nvim-telescope/telescope.nvim',
  'https://github.com/nvim-lua/plenary.nvim'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end
```
Then run `:Telescope` and start searching

### Expected behavior

These bugs not happening

### Neovim version (nvim -v)

v0.10.0-dev-954+g008154954

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux 6.4.12-arch1-1

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

build from repo

**Comment by lewis6991** [comment]
Please! Stop using lazy.nvim in minimal reproduction steps and follow https://github.com/neovim/neovim/wiki/Minimal-reproduction-template

**Comment by wookayin** [comment]
It would have probably been fixed by #24889

**Comment by catgoose** [comment]
> It would have probably been fixed by #24889

Wilder stills removes topline after that pr

**Comment by bfredl** [comment]
PR https://github.com/neovim/neovim/pull/24913 to fix issue with line disappearing from current buffer (https://github.com/neovim/neovim/issues/24911)

More work on topline behavior (first displayed line in window): https://github.com/neovim/neovim/pull/24912

These seem to be related to many reported plugin issues, but doesn't fix telescope yet.

**Comment by catgoose** [comment]
> Member

Thanks, that fixes the issues with wilder.

**Comment by altermo** [comment]
As all the plugins work with the latest release of neovim, I'm closing thins issue.
