### ISSUE TITLE
Arbitrarily invoke insert mysterious words when Japanese(or not english lauguege) input

### ISSUE THREAD

**Issue by zchee** [neovim/neovim#3094]
Hi,

I'm troubled by arbitrarily invoking insert mysterious words when Japanese(or not English language) input on insert mode.

Tried typing Japanese *Hiragana* ([see wikipedia](https://en.wikipedia.org/wiki/Hiragana)) words.
After that, converting *Hiragana* to *Kanji* ([see wikipedia](https://en.wikipedia.org/wiki/Kanji)) words.
This behavior is similar to the operation of the Omnifunc completion.

Finally, select any *Kanji* words and hit `<Enter>`.
but, Occasionally insert mysterious words on current buffer.

What happened?

For more information, see the screencast.
[Screencast on Dropbox](https://dl.dropboxusercontent.com/u/145880230/screencast/issue%3Aneovim%233094.mp4)

**Comment by justinmk** [comment]
I see that some of the characters are broken, but can't see the byte literals clearly in the screencast, 

Can you post the literal text that you are trying to insert? That is, please post the text that you *expect* to insert (not the incorrect text).

**Comment by zchee** [comment]
@justinmk I think that caused by just maybe https://github.com/neovim/neovim/issues/3092.
I will try to test again.

**Comment by justinmk** [comment]
@zchee We can close this then?

**Comment by zchee** [comment]
@justinmk 
Copy insert text.
but, not UTF-8 style :(
����

gist https://gist.github.com/zchee/63e546a9126482d57165

**Comment by zchee** [comment]
@justinmk 
and,

```
echo -n '�' | hexdump
```

result,

```
0000000 ef bf bd
0000003
```

**Comment by zchee** [comment]
@justinmk Thanks re-open issue!
Is there anything that I can be your help?

**Comment by justinmk** [comment]
Need more info.

- Does Hiragana have the problem also, or only Kanji?
- Does it work in Vim?
- What is the Unicode code-point (*not* the byte sequence) of the characters you are trying to insert?
    - You can find the table of codes here: http://unicode.org/charts/ (it has Hiragana, but I don't see Kanji there)
- If you insert in the characters in your shell (before starting nvim) do they appear correctly?
- Are you sure the font you are using supports the characters you want?

The characters you posted aren't displayed my web browser. Also, what is the completion menu you are using?

**Comment by zchee** [comment]
@justinmk 
Sorry, late reply.
This condition does not always happen.

> • Does Hiragana have the problem also, or only Kanji?

Hiragana and Kanji (and Katakata, all japanese languege).
Both issue.

> • Does it work in Vim?

Original Vim is works fine.

> • What is the Unicode code-point (not the byte sequence) of the characters you are trying to insert?
You can find the table of codes here: http://unicode.org/charts/ (it has Hiragana, but I don't see Kanji there)

In screencast point 1:15, I inputed ”お” is unicode `u304A`.
hexdump result,
```
0000000 e3 81 8a
0000003
```

> • If you insert the characters in your shell (before starting nvim) do they appear correctly?

No problem.

> • Are you sure the font you are using supports the characters you want?

Does this question points to the thing of the font file(otf, ttf, ttc) ?
e.g. https://github.com/adobe-fonts/source-han-code-jp
Download url: https://github.com/adobe-fonts/source-han-code-jp/archive/1.004R.zip
Be careful. This file size 52MB because it contains all `Kanji` words.

> The characters you posted aren't displayed my web browser

I do not know why you do not see :(

>  Also, what is the completion menu you are using?

Does this question points to the thing of the neovim front-end?
I use `YouCompleteMe`.
If your question is pointing to the fact of this image, it is OS X El Capitan original IME.

![untitled](https://cloud.githubusercontent.com/assets/6366270/9706340/f0f2fd02-551c-11e5-93a0-c3e01d6c5d3d.png)

**Comment by justinmk** [comment]
@zchee can you try https://github.com/neovim/neovim/pull/3246

**Comment by zchee** [comment]
@justinmk Tested #3246 ,but It has been displayed the mysterious string again... :(
but but, #3092 issue is fixed!!
Thank infomation :)

Is there anything that I can be your help?

**Comment by zchee** [comment]
BTW, I typed おおおお, result
![screen shot 2015-09-07 at 9 59 58 am](https://cloud.githubusercontent.com/assets/6366270/9707569/50344d1e-5547-11e5-91d2-095bffeb8b02.png)

It displayed `<8a>` after `？`.
`お` hexdump last words is `8a`.
It might have been implicated something.

**Comment by zchee** [comment]
@justinmk Hi

masterr branch's neovim is this issue has been resolved!!
but, What's happened?

If you have time, I want you to tell me commit, which may be the cured reason.
Thanks.

**Comment by justinmk** [comment]
@zchee This is resolved, right?

**Comment by justinmk** [comment]
Maybe related: https://github.com/neovim/neovim/issues/3168

**Comment by zchee** [comment]
@justinmk Thanks reply.
Solved. 

Close.

**Comment by hori-ryota** [comment]
I have also encountered a similar problem, but is this resolved?

Input
<img width="933" alt="input" src="https://user-images.githubusercontent.com/2936501/27262193-a5505c48-548c-11e7-9d06-de46e57bdce4.png">

Result
<img width="931" alt="result" src="https://user-images.githubusercontent.com/2936501/27262202-b4c0549e-548c-11e7-9dcf-49626845921d.png">

I tried followings but not solved.

* without tmux
* without iterm2
* `nvim -u NORC`
* without google ime (with default ime)
* without Karabiner
* with other PC (Mac)

Is there anything I should try?

**Comment by Shougo** [comment]
@hori-ryota You can test it on the several terminals.

**Comment by hori-ryota** [comment]
Buffers may be split when using IME and splited multibyte char. It seems to be confirmed keys with each buffer only.

example,

* buffer size is 4
* input chars `ああああ`
* `あ` is `e38281`

`ああああ` will be splited to  `e38281e3` `8281e381` `82e38182`

It was a report for the time being. I will continue to look it up.

**Comment by hori-ryota** [comment]
Can we reopen this issue?

**Comment by zchee** [comment]
@hori-ryota I’ll comment later.

**Comment by hori-ryota** [comment]
This trouble was avoided by the following settings.

```
set ttimeout
set ttimeoutlen=100
```

This problem seems to be similar to the problem concerning discrimination between cursor key and escape key.

Users using multibyte characters seem to have to be careful because garbled characters are made using default settings.

**Comment by Shougo** [comment]
@hori-ryota It is the problem of `ttimeout` is too short?
I think it should be documented in the documentation.
And it should be in `:CheckHealth` check.

**Comment by hori-ryota** [comment]
Yes, if `ttimeoutlen` is too short or zero, tk_getkeys is called with `force=true` and split multibyte char.
