### ISSUE TITLE
Error when lsp.util.open_floating_preview used in insert mode with default

### ISSUE THREAD

**Issue by MatthewKandiah** [neovim/neovim#31336]
### Problem

Using `vim.lsp.util.open_floating_preview` in insert mode with the default `opts` argument emits the following error on entering a character:
```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1347: scoped variable: Invalid window id: 1003
 stack traceback:
         [C]: in function '__index'
         /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1347: in function </usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1339>
```
The invalid window id is different each time. No such error is emitted on cursor move or on escaping to normal mode.

In reality I hit this when calling `vim.lsp.buf.signature_help`. I fixed the issue in my config by setting `opts = {close_events = {'CursorMoved', 'CursorMovedI'}}`. The default value uses those events and `InsertCharPre`, my guess is that inserting a character also moves the cursor, so two events are emitted, both try to close the floating preview, and one errors because it no longer exists. 

### Steps to reproduce

Minimal nvim config
```lua
function Open_floating_window ()
  vim.lsp.util.open_floating_preview({"line1", "line2", "line3"}, 'markdown')
end

vim.keymap.set({ 'n', 'v', 'i' }, '<C-h>', Open_floating_window)
```
Use the keymap to open a floating window. In insert mode, enter a character with the floating window open, and you'll see the error message. 

### Expected behavior

Close the window without an error.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1216+g9a681ad09e

### Vim (not Nvim) behaves the same?

I don't think this is applicable, since this is part of the lua api.

### Operating system/version

Linux Mint 21.3

### Terminal name/version

alacritty 0.14.0-dev (7077a5f4)

### $TERM environment variable

xterm-256color

### Installation

Build from repo

**Comment by telemachus** [comment]
Probably fixed by #31319. Try updating or applying that patch.

**Comment by MatthewKandiah** [comment]
I don't think it is fixed. I've pulled `master`, checked I can see the changes from #31319 in the source code, and rebuilt. I'm seeing the same error.

I've not worked with the neovim source at all before this, so just to be certain I'm not missing something silly, what I've done is:
- `rm -rf build`
- `make CMAKE_BUILD_TYPE=Release`
- `./build/bin/nvim -u {path to the minimal config included above}`

Update output of `nvim --version` from that build is `v0.11.0-dev-1226+gaf112e605d`

**Comment by telemachus** [comment]
I cannot reproduce, and I'm also on `v0.11.0-dev-1226+gaf112e605d`. Maybe try again after `make distclean`?

**Comment by MatthewKandiah** [comment]
Okay I've done 
- `rm -rf build`
- `make distclean`
- `make`
- `./build/bin/nvim -u {path to the minimal config included above}`
- `i` to enter insert mode
- `<C-h>` to open floating window
- `t` to type character t
And that still shows the error message

**Comment by telemachus** [comment]
I tried again as well, but I cannot reproduce the problem here. Sorry.

**Comment by MatthewKandiah** [comment]
No problem, thanks for looking into it

**Comment by glepnir** [comment]
I can't reproduce it it should be fixed. because in WInClosed the window is valid . this error message mostly looks like throw by prev version.

![Image](https://github.com/user-attachments/assets/31be5b4f-f72b-433b-8dd1-4b408cff1005)
