### ISSUE TITLE
Tab rearrange with mouse problem

### ISSUE THREAD

**Issue by comdvas** [neovim/neovim#3310]
Tab rearrange itself when I rearrange tab with mouse and after that I start to selecting text with mouse.
This tab will be on that position, on that I click on text.
Just click on tab and start select text works too.

**Comment by justinmk** [comment]
Need:

- precise steps to reproduce
- a descrption of your environment (OS, terminal)
- `:version` output

**Comment by comdvas** [comment]
Steps:
1. open several tabs (:tabnew)
2. click on header of tab №1 
3. then start select text in text area, but your cursor must be in position under tab №2 
4. tab№1 will move into place of tab№2 as if I rearrange it myself with mouse.

In vim it not happening

OS: debian 8 64bit
WM: i3wm 4.8
TERMINAL: lxterminal 0.2.0 , bash (config: https://github.com/comdvas/mydot/blob/master/bash/.bashrc)

I test this bug in clear version of neovim without my .nvimrc or plugins.

:version
```
NVIM 0.0.0-alpha (compiled Sep  6 2015 18:36:41)
Commit: ?
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -fstack-protector-strong -fdiagn
ostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/evgeny/Downloads/neovim-nightly/build/config -I/home/evgeny/Downloads/neovi
m-nightly/src -I/home/evgeny/Downloads/neovim-nightly/.deps/usr/include -I/home/evgeny/Downloads/neovim-nightly/.deps/usr/include -I/home/evgeny/Downl
oads/neovim-nightly/.deps/usr/include/luajit-2.0 -I/home/evgeny/Downloads/neovim-nightly/.deps/usr/include -I/home/evgeny/Downloads/neovim-nightly/.de
ps/usr/include -I/home/evgeny/Downloads/neovim-nightly/.deps/usr/include -I/home/evgeny/Downloads/neovim-nightly/.deps/usr/include -I/usr/include -I/h
ome/evgeny/Downloads/neovim-nightly/build/src/nvim/auto -I/home/evgeny/Downloads/neovim-nightly/build/include
Compiled by evgeny@vas

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/share/nvim"
```

**Comment by oni-link** [comment]
Problem seems to be in `normal.c:do_mouse()`:
After clicking into the tab bar `in_tab_line` is set to `true`, so that later mouse movements can move a tab. But now selecting text (`is_drag` is `true`) will move a tab, even when not in the tab bar anymore. This patch seems to fix it for me:

```diff
diff --git a/src/nvim/normal.c b/src/nvim/normal.c
index 5b35af9..0b1df5a 100644
--- a/src/nvim/normal.c
+++ b/src/nvim/normal.c
@@ -2088,7 +2088,7 @@ do_mouse (
       }
     }
     return true;
-  } else if (is_drag && in_tab_line) {
+  } else if (mouse_row == 0 && is_drag && in_tab_line) {
     c1 = TabPageIdxs[mouse_col];
     tabpage_move(c1 <= 0 ? 9999 : c1 - 1);
     in_tab_line = false;
```

**Comment by timtadh** [comment]
I can confirm that I have been experiencing this bug as well.

**Comment by justinmk** [comment]
If only a PR could be created with the patch given above ;)

**Comment by jamessan** [comment]
@timtadh What version are you using?  There was an upstream patch (7.4.857) that was supposed to solve this problem and didn't get merged until 0.1.3.

**Comment by timtadh** [comment]
I am using master but it was a few weeks old. I am trying this out now. Something, seems funky though so I am investigating.

**Comment by timtadh** [comment]
Things seem broken for me on master at the moment. I am trying regenerating the build from scratch.

**Comment by timtadh** [comment]
@jamessan on revision 4dcd19d9bc2417051ddbda177010ca8c0cb2cf73 which is tag v0.1.4 it is still broken and I can reproduce the issue. Applying the suggested fix from oni-link does indeed fix the problem. On master which is 999590b313ef32ca29c4ddba20c5b719730ee7ff there is strange behavior from the mouse in the terminal. For instance, if I open NerdTree I can't click on a directory to expand it as I should be able too. Because of the mouse weirdness in master, I can't say one way or another whether this issue is fixed.

**Comment by justinmk** [comment]
The nerdtree issue might be lack of "release" event, pending PR exists.

**Comment by timtadh** [comment]
@justinmk If you know what PR that is I will apply it and test. If I can confirm that both issues are fixed I will create a PR for @oni-link 's patch.

**Comment by jamessan** [comment]
https://github.com/neovim/neovim/pull/4874

**Comment by timtadh** [comment]
#4874 Does not fix the mouse wierdness I was experiencing. I did not try re-applying the fix for this issue.

**Comment by justinmk** [comment]
@timtadh I'm confused. Are you saying oni-link's patch for this issue causes a different problem, or only that you have 2 problems and only 1 is fixed?

**Comment by timtadh** [comment]
@justinmk : I am saying that on the current master I have 2 bugs. 

1. The bug in this thread. Also present in tag v0.1.4.
2. Another mouse bug present in master but not in tag v0.1.4. 

@jamessan : indicated that #4874 fixed the 2nd problem I am experiencing (mouse clicks not being registered reliably in say NerdTree esp. double clicks). However, #4874 did not fix the issue when I applied it on top of master @ 4dcd19d9bc2417051ddbda177010ca8c0cb2cf73 .

The fix provided by oni-link does indeed fix problem 1 when applied on top of tag v0.1.4. However, it is unclear to me if it fixes the problem on master do to other strange behaviors the mouse is exhibiting. 

I hope that answers your question. I am not familiar with the vim or neovim code base but happy to help diagnose the problems with guidance.

**Comment by sach1t** [comment]
Using the current code in master, I cannot seem to reproduce the bug. What oni-link said is correct, and the issue was fixed when adding the release event (pull request #4873) as `in_tab_line` then gets reset (line 2216 in normal.c).

**Comment by sach1t** [comment]
Also, pull request #4874 does include the code from #4873. So if applying that did not work... I am not sure what the issue is.

**Comment by timtadh** [comment]
Tomorrow I will try and do a bisect and figure out what the issue is with
NerdTree. Real life is getting in the way of doing very much programming
today.

**Comment by Quent42340** [comment]
Hi. I'm using neovim 0.1.5 on ArchLinux and this bug is still unfixed. Any news about it?

**Comment by justinmk** [comment]
@Quent42340 I think https://github.com/neovim/neovim/pull/4874 is ready so I'll merge it.

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/4874.

**Comment by comdvas** [comment]
Just checked, this bug is still exists. 
Fix by @oni-link is not actual anymore because the code has been changed.

:version
```
NVIM v0.1.6-287-g43309d1
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -f
diagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/evgeny/Downloads/neovim/build/config -I/home/evgeny/Downl
oads/neovim/src -I/home/evgeny/Downloads/neovim/.deps/usr/include -I/home/evgeny/Downloads/neovim/.deps/usr/include -I/home/evgeny/Downloads/neovim/.de
ps/usr/include -I/home/evgeny/Downloads/neovim/.deps/usr/include -I/home/evgeny/Downloads/neovim/.deps/usr/include -I/home/evgeny/Downloads/neovim/.dep
s/usr/include -I/usr/include -I/home/evgeny/Downloads/neovim/build/src/nvim/auto -I/home/evgeny/Downloads/neovim/build/include
Compiled by evgeny@vas

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/stow/neovim_161024/share/nvim"
```

**Comment by justinmk** [comment]
@comdvas Can you compare with a different terminal? Tab dragging works fine for me.

**Comment by comdvas** [comment]
@justinmk In xterm everything is ok. I tried in lxterminal and urvt and in these terminals this bug is appears. What would you recommend?

**Comment by justinmk** [comment]
@comdvas What version of [libvte](https://github.com/GNOME/vte) is your lxterminal using? There were many bugs in older libvte versions. In [several cases](https://github.com/neovim/neovim/issues?q=is%3Aissue+libvte+is%3Aclosed) we've found that problems went away after upgrading libvte.

**Comment by comdvas** [comment]
@justinmk lxterminal from debian using libvte 0.28.0 - the last with gtk2 support.
I tried roxterm-gtk3, which uses libvte 0.36.3 and no problems there. In roxterm-gtk2 the problem is exists.
I will use roxterm-gtk3, thanks for help.

**Comment by justinmk** [comment]
@comdvas Thanks for the follow-up!

**Comment by Nadrieril** [comment]
I am experiencing this problem too on nvim 0.2.0 and urxvt. I understand urxvt is not supported but I thought it could interest someone.
@oni-link 's patch does not apply directly but I adapted it and this fixes the problem.

**Comment by sach1t** [comment]
I will take another look at this with urxvt and the other terminals that are giving issues. Maybe I can find a workaround or something for it.
