### ISSUE TITLE
Gsoc: Remote SSH Plan

### ISSUE THREAD

**Issue by siddhantdev** [neovim/neovim#34257]
### Problem

Add support for remote editing through ssh to Neovim.

### Expected behavior

An interface which lets the user connect to a remote machine through ssh and edit files on it.

**Comment by justinmk** [comment]
## potential outline:

- user can select any "host" from their ssh config
  - nvim should avoid _parsing_ ~./ssh/config as much as possible. instead it should delegate almost everything to `ssh`. "parsing" may be needed to get the list of host names (but maybe there's a way to ask `ssh` itself to give us that list).
  - show a menu. user can select from the menu.
    - available as a `opt/` plugin. other plugins can use this to get a list of ssh host names.
- connect to ssh endpoint
  - system must have `ssh`. we will use that to connect.
  - start nvim on the remote ssh server.
      - then the local nvim will use `ssh` *tunneling* to connect to the remote nvim.
  - stop current nvim server without stopping the ui client.
      - skip this if other UIs are connected to the server.
  - "reattach" the ui client to the new remote nvim.
      - hint: see the `:connect` "Implementation" section [here](https://github.com/neovim/neovim/issues/5035#issuecomment-2343537003).



## out of scope:

- can the `:connect` menu [show local addresses](https://github.com/neovim/neovim/pull/34586#discussion_r2169881849), even on a remote machine? One way to do this might be for the UI to pass along locally-discovered addresses when it first connects to a remote.
    - If another server is started after connecting to a remote then it won't show up on the list. To address that, local Nvims could make rpc calls to remote Nvims when they startup.
- auto-install on remote
  - P0: auto-install nvim on the remote.
  - P1: if remote outbound network doesn't work, download locally then upload to remote.
  - P2: upload user's local config to the remote.

**Comment by justinmk** [comment]
Updated the outline above, and added "Implementation" outline for `:connect` [here](https://github.com/neovim/neovim/issues/5035#issuecomment-2343537003). Implementing `:connect` is a good starting point, because it is needed to connect to the remote ssh Nvim.

**Comment by PowerUser64** [comment]
A related plugin worth mentioning here is [remote-nvim.nvim](https://github.com/amitds1997/remote-nvim.nvim). Notably, remote-nvim.nvim can interface with docker containers and [devpods](https://github.com/loft-sh/devpod).

It would be good to consider potential overlap in functionality with plugins (like remote-nvim.nvim) when designing this, since there are many components in this that would be useful in making other remote editing plugins. (Eg. functions to help install nvim, copy config files, etc.)

Something else that I'm not seeing mentioned here is cleanup. If nvim is installed on the remote through any method, it would also be nice to have an easy way to remove it from the remote, potentially automatically. I'm imagining something like `rm -rf ~/.nvim-remote/` to clear all session data, along with something like a "RemoteDisconnectPre" event that could be used to run it before disconnect.

I think this would be very powerful if it were ever used in combination with something like the `:detach` feature that was proposed in #5035. Very exciting! Looking forward to seeing where this all goes.

**Comment by siddhantdev** [comment]
I have implemented the `:connect <address>` command and opened a PR here: https://github.com/neovim/neovim/pull/34586

**Comment by justinmk** [comment]
From discussion:

It probably makes sense for `:connect` to present both "nvim addresses" and "ssh hosts". 

```
1. localhost:8080
2. /var/run/nvim/foo
3. my.host1 (ssh)
4. foo.bar (ssh)
```

If an ssh host is selected, then it invokes the "ssh connect" codepath instead of just plain old "attach".

**Comment by LunarLambda** [comment]
> * nvim should avoid _parsing_ ~./ssh/config as much as possible. instead it
>       should delegate almost everything to `ssh`. "parsing" may be needed to get
>       the list of host names (but maybe there's a way to ask `ssh` itself to give
>       us that list).

Are we talking about `Match host ...` blocks in `~/.ssh/config` or the `~/.ssh/known_hosts` list?

The later is just a space-seperated list of `hostname hostkey-type hostkey-fingerprint` and could be parsed easily.

SSH itself does not have a way to list "all configured hosts" since it's possible to do things like `Match host *.example.com`.

While there are ways to get SSH to output the "effective config" for a given connection string, Match blocks are resolved at config parse time and are not included in any output.

Hypothetically, neovim *could* choose to keep its own known hosts file, by invoking `ssh -o UserKnownHostsFile=~/.ssh/nvim_hosts` or similar, then serving hostnames from that list when selecting.

**Comment by justinmk** [comment]
> Hypothetically, neovim _could_ choose to keep its own known hosts file,

No. The scope here is to present a menu of ssh hosts, similar to what vscode does, by (1) reading ~/.ssh/config and (2) remembering previously-used hosts.

**Comment by LunarLambda** [comment]
I briefly checked what VS Code does

It uses https://github.com/cyjake/ssh-config to parse the entire ~/.ssh/config and extract the `Host` sections to present the list of usernames.

EDIT: Missed the edit in the email notification!

**Comment by siddhantdev** [comment]
Update on the current project status:

The list of things to do is now:

- connect to ssh endpoint
  - system must have `ssh`. we will use that to connect.
  - start nvim on the remote ssh server.
- auto-install neovim on remote

I'm currently working on listing all configured hosts in `~/.ssh/config`. The current plan is to rewrite https://github.com/cyjake/ssh-config in Lua and use that.

**Comment by siddhantdev** [comment]
Progress update on the project:

`connect` is done and merged 🥳. There is still an issue with invalid arguments which is being tracked here: https://github.com/neovim/neovim/issues/34676

The ssh configuration parser has been written as well and is pending merge now, here: https://github.com/neovim/neovim/pull/35027

Things that are left to do:

- connect to ssh endpoint with connect with `:connect ssh://...`
   + I have made some progress on this and am currently working on it
- make `:connect` display available options when an address is not provided
   + This should not be too difficult to add after the serverlist fix: https://github.com/neovim/neovim/pull/34806
- ~~auto-install neovim on remote~~

**Comment by justinmk** [comment]
I moved "auto-install on remote" to the "Out of scope" section. Let's focus on the other items for the next 2 weeks.

We can just require that `nvim` already exists in the remote ssh system.

**Comment by siddhantdev** [comment]
Status update:

The pull request made here: https://github.com/neovim/neovim/pull/35569 adds the features that were remaining on the list, namely:

- connect to ssh endpoint with connect with `:connect ssh://...`
- make `:connect` display available options when an address is not provided

I still have to write tests for the `:connect ssh://...` case, currently exploring how to test for ssh stuff locally. Documentation also needs to be written for both the changes but the code does work.
