### ISSUE TITLE
Remapping ESC to 'jk' occasionally pollutes the buffer

### ISSUE THREAD

**Issue by ChickenOnAStick** [neovim/neovim#36050]
### Problem

I've had ESC mapped to 'jk' for years now and occasionally have an issue where, when I escape with jk, the buffer hangs for a second or two (time varies slightly for each occurrence) and then a bunch of junk ends up in my text file that I have to clear away. I'm not sure what exactly the rhyme or reason is, but it's often a single character repeated, or something I had yanked, or maybe something under my cursor.

About a week ago I realized it probably has something to do with ESC being remapped to jk. Going back to the old-fashioned ESC key appears to have eliminated the issue.

### Steps to reproduce

I cannot reproduce this bug consistently, or very often. The single commonality between each instance of it occurring is using 'jk' to ESC, and has done so since neovim was only a few months old. I've had this happen using foot, alacritty, urxvt, and gnome-terminal, with and without tmux, and without any nvim plugins at all.

### Expected behavior

When jk is mapped to ESC, it should escape cleanly.

### Nvim version (nvim -v)

0.11.4

### Vim (not Nvim) behaves the same?

No

### Operating system/version

ArchLinux

### Terminal name/version

Foot 1.24 (and others)

### $TERM environment variable

Foot

### Installation

Arch repos

**Comment by zeertzjq** [comment]
At which version did this issue start happening?

**Comment by ChickenOnAStick** [comment]
This began around the time neovim was only a few months old (if not earlier). I was an early adopter and it's always happened, just pretty rarely. It may not have even been in the official Arch repos when I first started using it.

**Comment by tokisuno** [comment]
Does this happen every session or every day? Do you have anything else that is bound beyond "jk" like "jkl"? What's the frequency of this? 

I only ask because it would help a lot if you could provide a screen recording of the actual issue with some sort of on-screen keyboard when it happens yk

**Comment by ChickenOnAStick** [comment]
Apologies for the lack of details, I just seem to have eliminated the problem by not mapping jk to ESC and thought somebody more knowledgeable than myself could triage the issue based on the info I provided. I'll reenable it and try to reproduce while being recorded. But this is something that may happen on a weekly basis, and I can't figure out what exactly triggers it, just that it has something, presumably, to do with the key timeout getting hung up.

**Comment by ChickenOnAStick** [comment]
Update. This does not appear to be related to remapping ESC to jk. I just had it happen again (finally). Unfortunately, I did not manage to record it. I do, however, have a screenshot:

<img width="2880" height="1920" alt="Image" src="https://github.com/user-attachments/assets/d15b2c7c-4c37-43c3-86fd-75b29c6ebfb5" />

I'm glad I finally caught this at least. See window in upper left on line 54. I was in Normal mode, pressed 'i8' and then this happened. To be clear, this has only ever happened with nvim (not vim), and I've had this happen occasionally since it's been in the Arch repos. I'm terrible at backing things up too, so I've had it happen with all sorts of nvim configurations, with and without plugins etc.

I'll try to catch this with asciinema.

**Comment by ChickenOnAStick** [comment]
Also, I still have this buffer open. If anybody knows a way to extract what keystrokes nvim saw getting put into it, I'll try to recover it.

**Comment by justinmk** [comment]
To capture all input you can define a `vim.on_key` handler.

**Comment by ChickenOnAStick** [comment]
I just had this happen on a Fedora Silverblue install from dnf, no plugins, in the 'Terminal' program. I've previously had it happen with Debian and Arch with various DE's, WM's and terminal emulators (while using plugins) but this was a clean nvim config (ie no special ESC sequences) in GNOME with all the default settings.

This time, I pasted something from the system clipboard (ctrl-shift-v, no clipboard manager, just the stock GNOME clipboard) and then pressed a movement key, where it dumped not just what I had pasted, but an entire word, over and over again.

I am unable to reproduce this behaviour. 

<img width="3504" height="1611" alt="Image" src="https://github.com/user-attachments/assets/41a03bba-5226-4df7-8470-996170a99f60" />

**Comment by justinmk** [comment]
would you mind mentioning the exact Nvim version 

https://github.com/neovim/neovim/pull/40585 was merged and will be in Nvim 0.13

**Comment by ChickenOnAStick** [comment]
NVIM v0.11.6
Build type: RelWithDebInfo
LuaJIT 2.1.1767980792
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O2 -g -DRELDEBUG -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -Wno-conversion -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto  -DUNIT_TESTING -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -DUTF8PROC_STATIC -I/usr/include/luajit-2.1 -I/usr/include -I/builddir/build/BUILD/neovim-0.11.6-build/neovim-0.11.6/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.11.6-build/neovim-0.11.6/redhat-linux-build/include -I/builddir/build/BUILD/neovim-0.11.6-build/neovim-0.11.6/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.11.6-build/neovim-0.11.6/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by justinmk** [comment]
even if we fixed this bug , as long as you use old versions, we can't "fix" it

**Comment by ChickenOnAStick** [comment]
Fair enough, but I was in a toolbox I hadn't in a while. Updating now...

**Comment by ChickenOnAStick** [comment]
Just had this happen to me again. This time I was going into replace mode and it spammed the same two numbers I punched in really quickly after hitting `R`. I'm not sure these updates help you guys much, but I figured I'd update the issue and at least confirm it still exists in 12.5. I'm going to try and start using asciinema to catch a recording of this, but please let me know if I can assist in any other way. 

<img width="1431" height="295" alt="Image" src="https://github.com/user-attachments/assets/b19a5247-5129-4a33-931c-3cc87ef99259" />


I'm on nvim 12.5 from dnf on Silverblue 44 using default repos.

**Comment by ChickenOnAStick** [comment]
... And it's happened again. Of course I wasn't running asciinema. But it's installed now and I'll be aliasing it to nvim. I seems to be happening when I switch modes, such as `caw` or `R`. TBH it's been a while since it's happened when I paste from system clipboard. 
 
<img width="2253" height="83" alt="Image" src="https://github.com/user-attachments/assets/179a8777-efd7-41d4-9907-0684df763327" />
