### ISSUE TITLE
spaces added to end of terminal pasted lines when using highlight ctermbg

### ISSUE THREAD

**Issue by lqueryvg** [neovim/neovim#4421]
- Neovim version: 0.1.2
- Operating system: CentOS Linux release 7.2.1511 (Core) 
- Terminal emulator: xterm or urxvt256c with TERM=xterm-256color
### Actual behaviour

Neovim adds spaces to the end of lines pasted from the terminal (with `Shift` and middle mouse button).
### Expected behaviour

No  extra spaces.
### Steps to reproduce
- Start nvim.
- Add (`a`) the the following lines of text into the empty buffer.

```
this is a line of text
this is a line of text
this is a line of text
```
- Apply the following highlight setting:

`:highlight Normal ctermbg=232
`
- Go into insert mode at end of file (`Go`)
- Hold down `Shift` and select the previously inserted lines of text with the left mouse button.
- Paste the selected lines of text into the end of the buffer using `Shift` & middle-mouse button.
- `Esc` to go back to command mode & navigate up (`k`) to the lines just pasted and use `$` to go to the end of each line.
- Observe that spaces have been added to the end of each pasted line, up to the width of the window.

Note: this doesn't happen with vim.

**Comment by justinmk** [comment]
I am guessing this is because of `set mouse=a`. Try it after

    :set mouse=

**Comment by lqueryvg** [comment]
@justinmk Wow. Quick response.

No it's the same.

So, to be specific, if I do `:set mouse=` just after starting nvim in my steps above, I get the same behaviour.

**Comment by lqueryvg** [comment]
Oh, and yes, actual spaces.

**Comment by justinmk** [comment]
@bfredl does this sound like any existing primary clipboard issue you know of?

**Comment by bfredl** [comment]
No. I don't think neovim does anything, rather the terminal emulator implements shift+Left select. I get the same behavior with vim with or without `mouse=a`. (urxvt 256 colors)

**Comment by lqueryvg** [comment]
@bfredl, that's correct; when you hold down `Shift` the mouse selection is handled by the terminal emulator, not neovim. And when I paste using `Shift` & middle mouse button, the characters inserted (including the extra spaces I'm seeing) are being pasted by the terminal emulator, which means that the extra spaces are already in the clipboard at this point. I can demonstrate this by pasting the selection into a vim (not neovim) session in another window, and I see the extra spaces.

Therefore, the problem is not with the paste, it's with the select.

Here's what I think is happening...

1.  The `:highlight Normal ctermbg=232` is drawing spaces on the screen in the background colour.

2. When I select the lines using `Shift` & left mouse, the terminal emulator is also selecting these spaces.

This doesn't happen with vim (VIM - Vi IMproved 7.4).

**Comment by lqueryvg** [comment]
I should point out that although this issue might seem obscure, I suspect a lot of people might be affected for the following reasons:

1. The `Normal ctermbg` setting can be found in many colour themes, for example I came across this problem when using https://github.com/nanotech/jellybeans.vim and I can see the setting in many of the themes supplied with the neovim package.
2. As a unix sysadmin working on multiple remote machines, I commonly need to copy-paste between  different windows running unconnected vim sessions, i.e. via the terminal emulator's selection buffer / clipboard.

I'm afraid that having spaces added to the selected / copied text in this way would make neovim unworkable as a replacement for vim in such situations.

**Comment by bfredl** [comment]
I get this in vim with my default color scheme but not with `vim -u NONE` so it seems highlighting dependent in vim as well. (but regardless of `mouse=a`)

**Comment by lqueryvg** [comment]
Ah, interesting. I wonder why *I* don't get this behaviour with vim ?
Perhaps a  bug that's been introduced or behaviour that's changed.
FWIW, I'm using vim 7.4.160.

I will experiment some more. But if this is expected behaviour from vim & neovim intends to be the same, then I'm doomed.

**Comment by bfredl** [comment]
I don't think we actively "intend" to behave like this, it is just that neither vim nor neovim can guarantee this to work anyway. Mean `set number` and `:vsp` and other features break this kind of terminal emulator select anyway so it should not be entirely unexpected that some highlight settings also can. True, it would be nice for this to work "more often" but I don't think this should be labeled a bug.

**Comment by lqueryvg** [comment]
Understood, but with `set number` and `:vsp`, at least the user can see the numbers or vertical split characters being selected by the mouse, so it comes as no surprise when they are included in the terminal selection.

But I would have hoped there'd be a way for vim & neovim to draw Normal ctermbg colours without writing spaces to the screen ? Clearly there *was* (or *is*) in the version of vim I'm using. Perhaps the only way ultimately to get seamless copy/paste would be for the terminal emulator and vim to work together in some way.

Anyway, here is a possible **workaround** which seems to work for me:

After loading my colourscheme from `.vimrc`, I've added the following:

`highlight Normal ctermbg=NONE
`

**Comment by carlocapocasa** [comment]
Confirm the workaround works.

@bfredl My opinion is also that this is a bug.

- the stated goal of nvim is to be a drop-in replacement
- it seems to happen on all modern linux terminals, not some ancient mainframe
- there was a moment where I almost switched back

Many thanks to the entire nvim team, I am thoroughly enjoying myself with nvim because of all the fresh air and compatibility

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/issues/4210

**Comment by justinmk** [comment]
The mechanism at work here is the "bce" terminal capability. It's terminal-dependent, and it's a huge mess: https://github.com/kovidgoyal/kitty/issues/160#issuecomment-346470545

Since https://github.com/neovim/neovim/pull/6799/commits/133ae5eeeff3b83e1a3e6da35b57dcdfb92287b0 (Nvim 0.2.1+) Nvim uses the BCE entry found in terminfo, if any.

**Comment by carlocapocasa** [comment]
Aw, great! Thanks!

**Comment by justinmk** [comment]
Assuming this is fixed. The difference between @bfredl and @lqueryvg possibly may be explained by terminfo, or a `t_xx` setting.

If you think this is not fixed please confirm you are testing HEAD and say the exact `:version` (or commit hash).

**Comment by bfredl** [comment]
Somewhat related issue: recognition of wrapped lines in xterm with shift+select seems to not work with nvim TUI. This was implemented here but probably needs to be moved to the TUI module: https://github.com/neovim/neovim/blob/1e7d5e8cdf9827978f42ea114cfd85f9d32b00eb/src/nvim/screen.c#L4276-L4315

Investigating as part of #8221

**Comment by baszoetekouw** [comment]
I'm still getting this isseu in neovim 0.3.1.  Works correctly on vim 8.01766 with the same vimrc.

**Comment by CarloWood** [comment]
Ever since I upgraded from vim to neovim this issue is a nightmare for me. It makes copying with the mouse from a window running neovim impossible.

I never suffered from this with vim.

Is this something that should be fixed in a later version than I have? Or do I need to provide more info?

:version                                                                                                                                               
NVIM v0.3.1                                                                                                                                            
Build type: Release                                                                                                                                    
LuaJIT 2.1.0-beta3                                                                                                                                     
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-M0l_b5/neovim-0.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate
-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL
=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-col
or=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-M0l_b5/ne
ovim-0.3.1/build/config -I/build/neovim-M0l_b5/neovim-0.3.1/src -I/usr/include -I/build/neovim-M0l_b5/neovim-0.3.1/build/src/nvim/auto -I/build/neovim-
M0l_b5/neovim-0.3.1/build/include                                                                                                                      
Compiled by team+vim@tracker.debian.org                                                                                                                
                                                                                                                                                       
Features: +acl +iconv +jemalloc +tui                                                                                                                   
See ":help feature-compile"                                                                                                                            
                                                                                                                                                       
   system vimrc file: "$VIM/sysinit.vim"                                                                                                               
  fall-back for $VIM: "/usr/share/nvim"                                                                                                                

(copy&pasted from neovim.. so sorry for the loads of spaces at the end of every line).

**Comment by CarloWood** [comment]
Note that this is with :set mouse=   (I never used anything else).
I have the problem when selecting multiple lines with my mouse, holding shift or not doesn't matter.
Doing :highlight Normal ctermbg=NONE  does not help / change anything.
For that matter, :syntax off  removes all syntax highlighting, but not the extra spaces after every selected line.

**Comment by justinmk** [comment]
Try the 0.3.4 release

**Comment by dirkson** [comment]
I still have this issue on the 0.3.4 release.

NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -g -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/neovim-0.3.4/build/config -I/builddir/neovim-0.3.4/src -I/usr/include -I/builddir/neovim-0.3.4/build/src/nvim/auto -I/builddir/neovim-0.3.4/build/include
Compiled by void-buildslave@a-hel-fi

Features: +acl +iconv -jemalloc +tui

**Comment by pancutan** [comment]
> Understood, but with `set number` and `:vsp`, at least the user can see the numbers or vertical split characters being selected by the mouse, so it comes as no surprise when they are included in the terminal selection.
> 
> But I would have hoped there'd be a way for vim & neovim to draw Normal ctermbg colours without writing spaces to the screen ? Clearly there _was_ (or _is_) in the version of vim I'm using. Perhaps the only way ultimately to get seamless copy/paste would be for the terminal emulator and vim to work together in some way.
> 
> Anyway, here is a possible **workaround** which seems to work for me:
> 
> After loading my colourscheme from `.vimrc`, I've added the following:
> 
> `highlight Normal ctermbg=NONE `

Awesome!
My tiny contribution is to assign a shorcut to you trick:

```
let mapleader = ","
nnoremap <leader>tr :highlight Normal ctermbg=NONE<CR>
```
Now with ,rt you can copy with mouse the selected text without trailing spaces.
Thanks buddy!
