### ISSUE TITLE
<MiddleMouse> leaves TERMINAL mode after paste, even if you map it to '<MiddleMouse>a'

### ISSUE THREAD

**Issue by cmcaine** [neovim/neovim#5479]
- `nvim --version`:

```
NVIM 0.1.5                                                                                                                     
Build type: RelWithDebInfo                                                                                                     
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wal
l -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=aut
o -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.
1.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovi
m/src/build/src/nvim/auto -I/build/neovim/src/build/include                                                                    
Compiled by builduser                                                                                                          

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui                                                     
```
- Vim (version: ) behaves differently? N/A
- Operating system/version: Arch
- Terminal name/version: rxvt-unicode256color
- `$TERM`: rxvt-unicode256color
### Actual behaviour

In terminal insert mode, pasting from the selection buffer with middle mouse causes the terminal to enter NORMAL mode.
### Expected behaviour

Pasting into the terminal should not change which mode I'm in. I tried to work around the problem with `:tnoremap <MiddleMouse> <MiddleMouse>a`, but even with this mapping I am returned to normal mode after a few pastes.
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:terminal
<paste some text with middle mouse, observe how mode changes>
```

**Comment by justinmk** [comment]
Can you test with 

    set mouse=a

And

     set mouse=

**Comment by cmcaine** [comment]
`set mouse=a` has the behaviour I described in the OP

`set mouse=`  has the expected behaviour, but obviously other stuff is broken.

**Comment by justinmk** [comment]
I am wondering if bracketedpaste mode is involved.

**Comment by cmcaine** [comment]
Do you think that :terminal doesn't know how to deal with bracketed paste?

**Comment by HarmtH** [comment]
Both ```<MiddleMouse>``` and ```<MiddleRelease>``` (and all other mouse events) exit terminal mode. Try to add ```tnoremap <MiddleRelease> <Nop>``` next to your ```tnoremap <MiddleMouse> <MiddleMouse>a```.

**Comment by cmcaine** [comment]
A good idea, but no more effective.

**Comment by cmcaine** [comment]
With some experimentation and a look through `src/nvim/terminal.c`, I was able to determine that what I thought was inconsistant behaviour is actually nvim detecting different kinds of mouse behaviour.

````
  tnoremap <MiddleMouse> <MiddleMouse>a
  tnoremap <MiddleDrag> <Nop>
````

Does pretty much what I want it to. The only remaining causes of odd behaviour are:

* Pressing middle mouse quick enough to trigger a double click event bypasses the mapping
* Sometimes the terminal buffer doesn't show the full line that has been pasted until the next keypress.

Double click isn't a problem in real use, and I can map it out with `tnoremap <2-MiddleMouse>`, I just mention it as something that might confuse anyone testing the behaviour.

The terminal sometimes not being redrawn is more annoying, but happens infrequently enough that I can live with it.

__Recommendation__: the mappings that I've written here should be default behaviour.

Bonus: I can get urxvt-style paste from clipboard (rather than selection) with these mappings:
````
  tnoremap <M-MiddleMouse> <c-\><c-n>"+pa
  tnoremap <M-MiddleDrag> <Nop>
````

**Comment by HarmtH** [comment]
But still I think terminal mode should be like insert mode with respect to mouse handling, so we should not leave terminal mode by default (including visual selections; we should get  -- (terminal) VISUAL -- ), .

**Comment by cmcaine** [comment]
That's not inconsistant with what I'm suggesting.

Pressing MiddleMouse while in insert mode in a normal buffer pastes and leaves us in insert mode. I'm suggesting Terminal mode should match that behaviour.

**Comment by cmcaine** [comment]
@justinmk I'm happy to put together another tiny pull request for this, but I can't find where default mappings should be put. Could you give me a hand?

**Comment by justinmk** [comment]
@cmcaine I guess you could throw in next to this: https://github.com/neovim/neovim/blob/master/src/nvim/main.c#L318-L329

    do_cmdline_cmd("tnoremap ...");
    do_cmdline_cmd("tnoremap ...");

That's pretty unsatisfying though, because we would be hiding a bug. Better to fix the bug.

**Comment by cmcaine** [comment]
This was fixed at some point before current master (0cab62ad6fc642c06e4249dccac092dd71b0cb3e).

Not going to git-bisect to find where it was fixed: I don't see how to tell make to just rebuild the dependencies when they change, so building nvim takes too long when skipping between versions.

Thanks to the mystery fixer :)

Closing.

**Comment by cmcaine** [comment]
I'd like to use my maps except when nvim version is > 0.2, but I can't see how to do that in vimscript without parsing `:version`. Is there a better way?

**Comment by justinmk** [comment]
You can use `if !has('nvim-0.2')` to check version older than 0.2+, see `:help feature-list`.

**Comment by cmcaine** [comment]
Thanks!

**Comment by eternaleye** [comment]
So I'm on Neovim v0.2.2, and I'm still seeing this issue - both in the terminal and under neovim-qt. No matter what `<MiddleMouse>` is bound to, using it in terminal mode ends up in normal mode. Even if I set it like this:

```Vim
tnoremap <MiddleMouse> <C-\><C-n>"*pa
```

it merely pastes, returns to terminal mode due to `a`... and then departs for normal mode again. This happens for `<MiddleRelease>` as well. Setting `mouse=` instead of `mouse=a` papers over the problem in the terminal since it then acts like normal input, but doesn't resolve the issue in neovim-qt.
